

TODO:
the car comes first. Then one can live anywhere, including all the hip areas of Cali.
*master the car life first.*

*conclusion: live and work in santa cruz until i get a car and/or find a good tech job in SF/Bay Area*
  - *stick to SF/Bay Area for startup work/learning/experience/network/relations*
  - stick to SC for rad nature-loving community living, or to just take a break from the Bay Area
  - *go back to NYC for the real deal*
  - can *try long beach city, though, more for warm weather, community, events, restaurant/cafe/delivery/event work*
    - need a car to live out there 'n find a place, as there are no hostels nearby

*TODO: add UCLA and UCI to jobs list*
  - it won't hurt trying 'em out.. i'm just here to make money anyway..


* liveable areas
  - ordered by the one i think i'd like the most

** big cities
*** YES NYC
- *the realest, dopest, passionate, no bullshit, pragmatic, just do it / DIY culture, respectful, hustle*
  - *even the tech businsses are more real!*
- *burns one out in a few months*
- *winters are FREEZING*
  - thus, can only go during the warmer times
    - especially after living in Taiwan..!!
- *i <3 NYC*
  - *everyone does*
*** NO LA
- see entry [below]
** places with a small-town vibe!: small-area cities, small towns (college-towns), city/metro neighborhoods
*** LIKELY santa cruz
  - *ocean AND mountains!!*
    - *redwood forests*
    - *nature lovers unite!!*
  - *most rad, by far*
    - *THE LAST HOPE* against building yet another boring suburb
  - *arts department has masters' classes for all of my interests:*
    - MS in playable media and games
      - part of theater department
      - notably *the only game degree in the UC system*
        - the other notable one is USC, which is private and super expensive
          - though, Jenova Chen went and possibly taught there..
    - MFA in film
      - *MFA in social documentary*
    - *MFA digital arts and new media*
    - B? in creative tech
      - the first
    - MFA in environmental art and social practice
    - *PhD in film and digital media*
      - can't be too many of these around..
    - also *MA/PhD in philosophy and history, including a PhD in feminist studies*
  - chill surfer/skater/bohemian culture
  - the tech people that love nature probably came here first
  - *white*
    - but hopefully offset by the school..?
  - landlords block any potential of it developing into a nice urban area
    - *only an extremely limited amount of shitty old houses are left*
  - *proximity to the bay area*
    - especially san jose jobs!!
      - would be a crazy commute though..
  - *cold :(*

*** YES long beach city (LA)
  - see entry under [LA]
  - *might actually have the best housing situtation out of all these in Cali*
  - *maybe worth trying..??*
*** YES SF
  - *BIG TECH MONEY*
  - *startup culture*
    - *still the center of startups* as of 2025
      - though, they likely move elsewhere after growing in size
    - now ai :/
  - noisebridge
  - *dog shit, human shit, needles, fentanyl crisis, homeless crisis*
  - mostly white, mixed with tech asians, a few latinos, chinatown (guangdong), and chinese (guangdong) owners of the west-side of SF
    - but no black people :(
  - ocean sucks
  - *good small parks culture*
    - holy shit San Diego sucks in comparison for having one massive tourist park!!
  - *golden gate park and city events*
  - *great sense of neighborhoods*
    - *small town vibe*
  - *great hikes*
    - *great day-to-day city life*
      - *i just miss the city life..*
  - city college
    - *FREE SCHOOL*
  - CCA
    - meh, nothing in Cali compares to NY's arts culture..
  - UCSF
    - just medicine
  - *get the feeling you are stuck in SF*
    - even with a motorcycle, those bridges are no fun, and have tolls
    - however, with some motorcycle gear, could be fun going north to marin county and south to santa cruz!
    - though, i kinda like that.. it keeps me finding new places 'n events in the city, again 'n again
  - *cold and foggy :/*
    - especially on the west-side of SF
    - very little land on the sunny south-east side..
  - *over-priced food*
    - unaffordable
  - winter must suck..
    - though, honestly, not much worse than San Diego.. just a bit more ranier
  - good grocery from that one chinatown street
    - now has a new tram line!
*** OKAY berkeley
  - suburban, but probably not as as bad as south bay/socal
    - probably closest to north park, san diego
    - a suburb with some essence of life in it.. though not much anymore
    - flea markets, thrift stores, leaving belongings you don't need on the street, garage sales, etc.
  - *boring AF*
    - *land bought up by boring, taste-less investors, so no one can do anything fun*
    - very limited by it's size and population, a similar problem to santa cruz and north park
    - really need to know where to go, make friends, attend house gatherings 'n parties
      - like an older, more mature SF
    - *also limited by morals, as the population is a bit more wiser, though, surprisingly, lacking in creativity, performance, arts*
  - the school's new (as of 2024) design department seems lame..
  - *mostly transient, half are international students*
  - no ocean, just the bay
    - not even close to the same vibe!!
    - *feel trapped :(*
      - SF's hikes are far better, and far more accessible too!
        - if it's ever warm enough to hike, that is..
    - and the west/bay-side actually gets cold, and even foggy!
  - screeching BART to SF not fun
    - nor is the bay bridge
  - *biotech industry..? if any??*
    - beyond the school, i'm really not sure if there is anything there..!!
  - *old liberal vibe*
    - stuck in the 60s-80s
    - *hatch-backs, station wagons, economical, conscious of waste*
    - *allied with old anarchists, 80s black panthers, zapatistas, indigenous conscousness, etc.*
    - ACAB (all cops are bastards)
    - *this may be reason enough to prefer it over San Deigo, which, outside of North Park, is very conservative, racist, white..*
      - at least here, there's a chance for community, allies, 'n friends..
        - or so, i thought..!
  - actually better weather than pacific beach and ocean beach in San Diego!

*** OKAY north park (SD)
  - see entry under [san diego]
*** davis
  - maybe more affordable?
  - *school is bikeable from town*
  - *entire school is bikeable*
  - *agriculture, vetrinary*
    - *agriculture =/= permaculture*
  - has the only design major, undergrad and grad
    - looks lame though..
    - berkeley has a master's in design too..
  - well-praised school
  - *smells like cow poo?*
  - *in the middle of nowhere*
  - *midwest climate: too cold and too hot, and no humidity :/*

*** san luis obispo
  - caltech
  - otherwise quite a conservative town in the middle of nowhere (industrial vineyards, other farms)
  - *prices seem much lower here than anywhere else i've seen..!*
  - avila beach / morro bay not far
    - seem really tasteless, just kitchy tourist stops

*** goleta/ucsb
  - just the school/college-town, actual town (santa barbara) is useless
  - expensive area, *extremely limited by housing*
    - *no one actually lives there.. as the only business is the school*
  - *school is on the beach! and has the mountains behind it!!*
  - *i'm on a beach!*

*** NO ocean beach (SD)
  - see entry under [san diego]
*** NO downtown oakland
  - see entry under [oakland]
  - oaktown?
** NO endless car-centric suburbia..
  - *well, all of Cali except SF and downtown areas is this.. :/*
*** OKAY LA
  - *TEMP: i'm reconsidering that this may actually be better than berkeley, SD, and SJ..*
  - has *by far the best energy out of all of California, from SD to SF*
    - *generally livelier, happier, more energetic people, the opposite of stingy*
      - though, also *burnt out*
    - *generally, easier to get along with, sharing a suburban hustling 'n bustling culture.. similar to how the NYC hustle brings people together*
      - *including whites, latinos, blacks, a few asians.. everyone! :D*
        - *including first generation immigrants!!*.. truly everyone mingles
      - *honestly, feels like living in middle-class Virginia Beach nieghborhoods, but with more positive energy, industry, ethnic enclaves, etc..*
        - this could be fun..!
    - *has a larger variety of people, beyond the tech people of the Bay Area*
      - *attracts artists, especially performance artists*
      - *attracts first generation immigrants, whom are similarly lively!*, as there are significant existing ethnic enclaves
    - has that *too big to fail* energy
  - nightmare lack of urban planning and architecture
    - *really have to look beyond this to see the beauty of it: the people and their cultures*
    - actually results in far more comfortable, spacious living/lifestyle, befitting the weather
      - houses are more spacious, with more luxurious bathrooms, kitchens, etc.
      - *the people have a very suburban, comfortable lifestyle too*
  - *industry and culture sucks compared to NYC: just too fake, flaky, stupid (except LBC, south-central)*
    - possibly the center of woke culture
    - just far more complacent, simple-minded businesses without assimilation nor innovation
  - *might actually have the best weather in Cali..*, for sub-tropical people like me, asians, blacks, 'n latinos
    - *feels much warmer than san diego, with less wind, though still retaining a good ocean breeze* to clean the air
    - *can stay outside at night, nearly all year*
      - *can motorcycle/bike at night too*
        - actually easy and comfortable (weather) to drive at night, even by motorcycle.. feel calm, though people do speed through the night..
      - *perfect porch/patio weather*
  - *possibly has the greatest amount of affordable housing among the most sought out places to live in California*
    - *some places go for $650/month!!* (Carson)
    - quite a few places under $1000, which is far more rare in SD (all of it), Bay Area, and possibly Santa Cruz
    - *lower minimum wage, average wage, and professional wage, especially in tech*
**** *has by far the most amount of distinct neighborhoods, especially ethnic ones:*
    - *LA is a microcosm of California*
      - basically, the rest of SoCal, and even NorCal (except SF and SC), can be found in LA:
    - *but most suck: are exclusive, ethnic-based, traditional or class-based*, with LBC as one of the rare few exceptions:
***** YES *LBC*
- *the only thing good about LA..??*
- *oakland on the sea*
  - similar demographics: black, south-east asian, *pan-gender*
    - lots of young people, especially students
  - similarly ghetto: homeless, drugs, crime
    - though, possibly less crime than Oakland..
  - similar to east coast cities: philadelphia, baltimore
    - overshadowed by a nearby bigger city, port, black population, lively music 'n arts, etc.
- *a microcosm of LA, and therefore California*
  - a mix of good and rough areas, making it a prime place to start busineses, especially for the surrounding bedroom Asian neighborhoods:
    - those surrounding areas are not fun to live in.. best to stick to the LBC and retain community relations
    - westminster is old Vietnamese money/families, complete with old retired dudes playing chess at cafe/gambling dens
    - garden grove is old Korean money/families
      - all are sprawling, strip mall suburbs
    - carson has a Filipino population
    - chinese people seem to be all around too..
- long beach
  - can easily drive/bike/walk up to several parking lots right next to the beach, like ocean beach: simple satisfaction for the lazy, *i actually love it!*
    - lots of people playing black music! :D
  - *the air is much warmer and less windier than san diego, reminds me of Taipei!!*
  - *the water is much calmer*, thanks to it facing south, like a bay, *and it calms me down too :)*
  - can't swim here
    - *the LA river dumps out all it's shit here, and there's a huge harbor*
    - maybe okay to dip your feet in..?
- *terrible traffic in every direction*
  - thus, you are trapped in there..
    - but you don't want to be anywhere else anyway..
    - tough to get to north-west LA, and impossible(?) to get to north-east LA, however:
    - *has the blue line to downtown (can transfer at main station), north-east LA, SGV, etc.* in case of an event
      - just have to think of it as riding the Caltrain in the Bay Area.. it's a very very long-distance train..
      - frightening to go on the wrong time, but maybe alright on the weekends and during events..??
- has some more beaches nearby: seal beach, bolsa chica beach, then huntington beach (costs $15 to park..!)
- *possibly even better weather than oakland, as you get the ocean wind!*
- snoopy d o double-g
***** [?] west/ocean-side LA
- maybe too white.. rich white like san diego
- venice beach
  - like ocean beach
- santa monica
  - MAYBE *silicon beach*
    - *UCLA*
    - *the best campus and food*
      - *TODO: hmmm, maybe not a bad place to work.. i mean, if you're going to be on the campus everyday anyway..*
    - near hip hollywood, or homeless hollywood.. and burnt malibu/santa monica
      - interesting.. but seems to only be huge companies, not a startup hub like SF 'n NYC..?
***** [?] north-east LA
- like berkeley?
- looks quite boring... maybe too white..??
***** [?] pasadena/south-pasadena
- like palo alto?
- also looks too boring, with big boring financial company headquarters..
- adjacent to SGV
***** NO chinatown (in dtla)
- tiny, as in a few blocks..
***** NO downtown
- like san diego's: garbage
***** NO the rest of LA / endless suburbia
  - like south bay and asian suburban in san diego, but flatter, and seemingly more endless, as nature is further away
  - *endless tract houses 'n strip malls, welcome to car city*
****** NO north OC?
- vietnamese, koreans, filipinos, chinese, etc.
****** NO SGV
- *SGV scared me.. these are not the Asians i was lookin' for..*
- chinese, including taiwanese, suburbs
  - boring
****** NO SFV
- latino, white
  - equally boring, with less culture
****** NO south OC
- rich, old money Asians and whites
- *generally considered the most boring part of LA, and possibly California*
- UCI
  - shit campus, similar to UCSD
  - *highest amount of asians* out of all the UCs

*** [?] san jose / south bay area
  - *OC (also called "south bay"), but with even more tech bros, and no girls, at all: man jose*
    - rich, boring asian tract-house suburbia, like mira mesa/clairemont/etc. in san diego
  - at least people actually live here though.. compared to transient berkeley and SF..??
    - not a great thing, as i saw in the suburbs of san diego..
  - a useless downtown
  - no beach..? what about mountains..? waterfalls? rivers??
    - i think i'd feel trapped here..
  - *tech work / BIG TECH MONEY*
    - the boring, corporate kind.. (startups are in SF, NYC, a little in LA/seattle)
  - *taiwanese tech scene*
    - see taiwanese facebook groups
  - *fremont*
    - *maybe has the most amount of indians AND taiwanese (200k+)*

*** NO san diego
- *basically, a duller, mellow, less cultured (diversity and ways of living/thinking) LA with nicer beaches and cleaner, newer development*
  - *lacks the energies of: artist culture of LA, tech-startup culture of SF, and research culture of Berkeley 'n Stanford*
  - *the beach alone makes it much more livable than suburbs without beaches*
  - still $1000 minimum for a room in a house/apartment
- transient population
  - lots trying to move in, just as many getting out..?
  - lots living in RVs / cars in/nearby RV parks
- tourists
  - not so many..
  - they stick to the beaches though.. and bring in easy money!
  - and probably bring the prices up too..
- *chill surfer/skater/bohemian culture*
  - gets old.. *i prefer the energy of the city: NYC, and probably even LA todo
- *car-camping culture*
  - *RV camps, park next to beach, everything!*
  - *truly stress free*
- school (UCSD) is lame, STEM only..
  - the school's campus is also lame: modern 1960s office buildings, car-centric
  - kinda in the middle of rich areas: surrounded by the beach, torrey pines, la jolla, small hill/valley neighborhoods
  - *influenced/created biotech industry*
    - which is also lame..
- SDSU (SD state) is a party school, not competitive
- jobs pay less than LA and Bay Area, yet the price of housing is the same

**** neighborhoods
***** OKAY north park
  - *hip, young, lively, liberal, subruban-bikeable small town*, most sim
    - lots of indie shops 'n restaurants (and not in strip malls!!)
      - though, still quite strip-malley around hillcrest and a few other areas..
    - a little strange though, like a suburban neighborhood turned hot-spot, like berkeley..
      - still made for cars
    - still quite white.. though, a good amount of latinos from the east/south-east, and asian kids from the north too!
  - *perfect location*:
    - *in-between bedroom asian and latino neighborhoods*, where you can get real food.. though, it's all in *over-priced suburban strip malls..*
    - *close to ocean beach and mission/pacific beach!*
      - *yet far enough to avoid the cold, coastal weather*

***** NO ocean beach
    - *a small, dumpy, beloved beach-town of it's own..*
    - *like haight st., can get old quick*, though, still cool, as far as music performances go
    - very white
      - *i'm afraid, too white for me.. too mono-culture, too american*
    - *the water is COLD*
    - very competitive housing
    - *exclusive neighborhood*
    - *very often has weird cold beach weather*
***** NO pacific beach
    - *boardwalk/beach*
      - unaffordable to have anything cool on it
      - *still, just great to have tho.. everyone comes out to this one!!*
    - neighborhood has all the major grocery stores
    - insecure frat boys, proud boys (racists), and military boys fighting
***** NO the rest of san diego
- *culture-less*, in diversity and ways of thinking/living
- *strip mall and white-painted SUV subrubs, like an extension of LA*
  - *new boring tract homes inland/north-east, and still a million minimum..*
- *no black people in most of San Diego??*
  - *this really kills the liveliness of SD..*
****** [?] latino neighborhoods
- *more diverse, including a few black and filipino enclaves*
****** NO asian neighborhoods
- at 3-5x the price of VA Beach..
  - not the asians i'm interested in!!
    - *though, they do remind me of myself..: suburban, computer-oriented*
- a cooler/chiller/newer alternative to OC..?
  - but without the community, industry, creativity, etc., also much like VA beach
****** NO north county
- *endless beaches, all bought up, owned by and live in by white people*
  - mostly rich white families (with businesses elsewhere?) with boats, SUVs, and other boy toys
- similar to west LA (manhattan/hermosa beach), but newer/later history
- oceanside
  - may be the exception, with *a great weekly street market* (biggers than ocean beach!)
    - maybe people from the inland areas come out for the hustle..
  - or maybe not, still appears to be bought up by investors, and *has a lot of big, ugly, hotels 'n apartment buildings..*

*** NO oakland
  - *??*
  - crime scared most people and economy away
    - including the long-enduring chinatown
  - seems for young, hip people.. too young 'n hip..
    - *provides a good counter-balance to berkeley, with street smarts*
    - k-town def for kids
    - lots of shops in downtown also cater to the hip youth
  - *black american culture*
  - actually good weather
  - beyond downtown is boring suburbs, without the ocean
    - dyin' of thirst
    - *fruitvale has a lot of latino people vending food out on parking lots!!*
* unliveable areas
  - basically, anything north of SF, as it gets more cold, cloudly, rainy, *depressing*, especially beyond the summer months
    - however, beautiful during the summer!
  - also, it becomes very white, as they are the only ones who can tolerate such miserable weather, and their own race / lack of other races
** portland
- rainy
  - more rainy than seattle!?
- cloudy
- white
  - culture-less
** seattle
- tech hub
  - microsoft
- university of washington
  - a legit public/state uni
- cloudy
  - no sun for several months during the winter half
- rainy
- white
  - though less white than portland..? thanks to the tech hub?





* ride back up the coast
https://bestneighborhood.org/race-in-san-diego-ca/i
  - a great site to see the racial divide in America, and find liveable places amongst other minorities
  - all white along the coast, no minorities in north county
    - except a valley inland from oceanside: vista, san marcos, escondido
  - asians, mostly east asians, are stuck in the middle, upper-class suburbia in mira mesa, sorrento valley, etc. super boring. they go to convey to eat out
      - had a bad history with the chinese, with chinatown taken down for city renovations
  - tiny filipino population stuck in bay terraces, surrounded by latino nieghborhoods and the naval base
  - south and south-east is all latino! and a few black people
    - probably the only diverse place to live.. with low-income housing

LA
  - *most diverse, by far, makes San Diego look like a joke, until south Bay Area*
  - *long beach, only beach area that's not white (black, latino, and south-east asian!)*
  - asians in:
    - notably divided by race
    - san gabriel, rowland heights/diamond bar hills, eastvale
      - FAR from everything!.. but they built their own world, i guess...??
    - *OC: irvine, viet in garden grove and westminister, artesia, NE of buena park*
      - *access to the better beaches, LBC, and DTLA. not bad..*

*oxnard*
  - latino
    - try it out..?

no asian until near UCSB

santa maria
  - latino

SLO
  - all white

hwy 101: soledad, salinas
  - all latinos

*watsonville*
  - all latino
  - good stop before santa cruz..

bay area
  - san jose, fremont, hayward, tri-valley
  - vallejo

sacramento
  - south of sac, in elk grove

NOTHING UNTIL SEATTLE
  - a few sprinkles in portland, but likely too gloomy, rainy for most asians






* random research
** reddit tidbits
https://www.reddit.com/r/aznidentity/comments/vjg4h6/some_observations_about_the_bay_area_from_an_la/
  - hmmmm, super interesting sub-reddit


an interesting bit on LA history..:

Just to put the SGV into perspective. Housing segregation was still a thing well into the 1980s. In many SGV ghetto areas, it was 5% to 10% Asian in the late 19th and early 20th century (and majority Mexican), when it was more agricultural. They lived in work camps at first, as contract labor. These camps became ghettos. So the area was prepped to become the SGV it is today, because of these seed communities.

Read this: https://imdiversity.com/villages/asian/history-of-asians-in-the-san-gabriel-valley/

That's also why the SGV was never really fully white. Nor was it ever fully considered "LA", because it was never able to wipe out these old Mexican and Asian populations. Also, some of the original whites into the area, like Temple and Workman, sided with Mexico in the Mexican-American war, and bailed out after the war.

You don't see all these roots anymore, because a lot of the people were Japanese, and put into the concentration camps during WW2, and the communities were wiped out. Also, there were Chinese camps, and towns, and those got burnt or buried. There was also a Korean town, I think, in the Inland Empire, and that's also gone.

Also, Chinese have been in the City of LA since the 1850s. By 1870s, there was a Chinatown of around 200 people. Then there was the massacre. Later, that small Chinatown was wiped out by the train station and freeway.





It is related to the % Whites in neighborhoods.

The most un-Asian/white-washed/self-hatred places are all the suburbs over 80% Whites.

The most AZN places are somewhere like Honolulu (16% Whites) , enclaves in and around LA ( Monterey Park 4% Whites) , and enclaves in NYC ( Sunset Park 10%, Flushing 9%)

Let me make it clear, it's not about % of Asians, but % of Whites.

Places like Irvine, West Bay, Seattle, Vancouver, despite with large Asian population, are very different from Honolulu or LA ( at least currently) . Because the % of Whites is still very large.
