

TODO:
the car comes first. Then one can live anywhere, including all the melting pot areas of Cali.
*master the car life first.*

*conclusion: live and work in santa cruz or long beach(!!) until i get a car and/or find a good tech job in SF/Bay Area*
  - *stick to SF/Bay Area for startup work/learning/experience/network/relations*
  - stick to SC for rad nature-loving community living, or to just take a break from the Bay Area
    - not sure if this is worth doing, as i already have Taiwan/Asia for nature reasons..
  - *go back to NYC for the real deal*
  - can *try long beach city, though, more for warm weather, community, events, ethnic communities, restaurant/cafe/delivery/event work*
    - need a car to find housing there, as there are no hostels nearby :(

*TODO: add UCLA and UCI to jobs list*
  - it won't hurt trying 'em out.. i'm just here to make money anyway..
  - though, i've heard irvine is the most boring place in LA.. :/
  - and unfortunately, UCLA is surrounded by rich areas: beverly hills, malibu, west-side LA, hollywood


* liveable areas
  - ordered by the ones i like or think i'd like the most

** big cities
*** YES NYC
- *the realest, dopest, most passionate, no bullshit, pragmatic, just do it / DIY culture, respectful, hustle*
  - *even the tech businsses are more real!*
- *burns one out in a few months*
- *winters are FREEZING*
  - thus, can only go during the warmer times
    - especially after living in Taiwan..!!
- *summers are uncomfortably hot 'n humid*
  - *similar to Tawain, but far more difficult to endure, as unlike Taiwan, convenient food 'n drinks will kill your finances*
- *i <3 NYC*
  - *everyone does*
  - i respect it too
*** NO LA
- see entry [below]
** places with a small-town vibe!: small-area cities, small towns (college-towns), city/metro neighborhoods
*** YES long beach city (LA)
  - see entry under [LA]
  - *might actually have the best housing situtation out of all these in Cali*
  - *worth trying..!!*
*** OKAY SF
  - *BIG TECH MONEY*
    - the only reason to be here
  - *startup culture*
    - *still the center of startups* as of 2025
      - though, they likely move elsewhere after growing in size
    - now ai :/
    - *requires much experience, skill, and interest*
  - noisebridge
  - *dog shit, human shit, needles, fentanyl crisis, homeless crisis*
  - mostly white and older guangdong chinese (chinatown, *west-side of SF*, southern parts of SF, daly city), mixed with tech asians, a few latinos (mission, daly city?), filipinos (33% of daly city: ~34,000), white gays (castro)
    - no black people :(
    - *this demographic is really meh*
  - *beach sucks*
    - cold, windy, sand in your eyes, freezing cold water
  - *good small parks culture*
  - *golden gate park and city events*
  - *great sense of neighborhoods*
    - *a great small town vibe for the whole city too*
  - *great hikes*
    - *great day-to-day city life*
      - *i just miss the city life..*
  - city college
    - *FREE SCHOOL*
  - CCA
    - meh, nothing in Cali compares to NY's arts culture..
  - UCSF
    - just medicine
  - *get the feeling you are stuck in SF*
    - even with a motorcycle, those bridges are no fun, and have tolls
    - however, with some motorcycle gear, could be fun going north to marin county and south to santa cruz!
    - though, i kinda like that.. it keeps me finding new places 'n events in the city, again 'n again
  - *cold and foggy :/*
    - especially on the west-side of SF (past the panhandle)
    - very little land on the sunny south-east side
      - and therefore over-priced for shitty housing
  - *over-priced food*
    - unaffordable
  - *highest minimum wage*
  - winter must suck..
    - though, honestly, not much worse than San Diego.. just a bit more rainy
  - good grocery from that one chinatown street
    - now has a new tram line!
*** LIKELY santa cruz
  - *ocean AND mountains!!*
    - *redwood forests*
    - *nature lovers unite!!*
  - *most rad, by far*
    - *THE LAST HOPE against building yet another boring suburb filled with corporate crap*
  - *arts department has masters' classes for all of my interests:*
    - MS in playable media and games
      - part of theater department
      - notably *the only game degree in the UC system*
        - the other notable one is USC, which is private and super expensive
          - though, Jenova Chen went and possibly taught there..
    - MFA in film
      - *MFA in social documentary*
    - *MFA digital arts and new media*
    - B? in creative tech
      - the first
    - MFA in environmental art and social practice
    - *PhD in film and digital media*
      - can't be too many of these around..
    - also *MA/PhD in philosophy and history, including a PhD in feminist studies*
  - chill surfer/skater/bohemian culture
  - the tech people that love nature probably came here first
  - *white*
    - but hopefully offset by the school..?
  - landlords block any potential of it developing into a nice urban area
    - *only an extremely limited amount of shitty old houses are left*
  - *proximity to the bay area*
    - especially san jose jobs!!
      - would be a crazy commute though..
  - *cold :(*

*** NO berkeley
  - suburban, but probably not as as bad as south bay/socal
    - probably closest to north park, san diego
    - a suburb with some essence of life in it.. though not much anymore
    - flea markets, thrift stores, leaving belongings you don't need on the street, garage sales, etc.
  - *boring AF*
    - *land bought up by boring, taste-less investors, so no one can do anything fun*
    - very limited by it's size and population, a similar problem to santa cruz and north park
    - really need to know where to go, make friends, attend house gatherings 'n parties
      - like an older, more mature SF
    - *also limited by morals, as the population is a bit more wiser, though, surprisingly, lacking in creativity, performance, arts*
  - the school's new (as of 2024) design department seems lame..
  - *mostly transient, half are international students*
  - no ocean, just the bay
    - not even close to the same vibe!!
    - *feel trapped :(*
      - SF's hikes are far better, and far more accessible too!
        - if it's ever warm enough to hike, that is..
    - and the west/bay-side actually gets cold, and even foggy!
  - screeching BART to SF not fun
    - nor is the bay bridge
  - *biotech industry..? if any??*
    - beyond the school, i'm really not sure if there is anything there..!!
  - *old liberal vibe*
    - stuck in the 60s-80s
    - *hatch-backs, station wagons, economical, conscious of waste*
    - *allied with old anarchists, 80s black panthers, zapatistas, indigenous conscousness, etc.*
    - ACAB (all cops are bastards)
    - *this may be reason enough to prefer it over San Deigo, which, outside of North Park, is very conservative, racist, white..*
      - at least here, there's a chance for community, allies, 'n friends..
        - or so, i thought..!
  - actually better weather than pacific beach and ocean beach in San Diego!

*** NO north park (SD)
  - see entry under [san diego]
*** [?] davis
  - just a college-town, *not a place to set roots in*
    - 66k population, 40k students, just enough to support the school 'n town..
    - OKAY for work
  - maybe more affordable?
  - *school is bikeable from town*
  - *entire school is bikeable*
  - *agriculture, vetrinary*
    - *agriculture =/= permaculture*
  - has the only design major, undergrad and grad
    - looks lame though..
    - berkeley has a master's in design too..
  - well-praised school
  - *smells like cow poo?*
  - *in the middle of nowhere*
  - *midwest climate: too cold and too hot, and no humidity :/*

*** NO san luis obispo
  - calpoly
    - eh..? *sounds boring.. like computer science departments*
  - otherwise quite a *conservative* town in the middle of nowhere (industrial vineyards, other farms)
    - despite latinos living and working in surrounding towns and industrial farms, the core population is conservative white, as in east San Diego white
      - 20% latino, *3.7% asian* (and likely nearly all students)
  - *prices seem much lower here than anywhere else i've seen..!*
    - save LA
  - very small
    - *feels like it could become boring very very quickly..*
  - avila beach / morro bay not far
    - seem really tasteless, just kitchy tourist stops
    - surrounded by beach ghost-towns, bought up by investors

*** [?] goleta/ucsb
  - just the school/college-town (just enough people to support the school), actual town (santa barbara) is useless
    - and thus, *no roots*
    - OKAY for work
  - expensive area, *extremely limited by housing*
    - *no one actually lives there.. as the only business is the school*
  - not bikeable..?? :/
  - *school is on the beach! and has the mountains behind it!!*
  - *i'm on a beach!*

*** NO ocean beach (SD)
  - see entry under [san diego]
*** NO downtown oakland
  - see entry under [oakland]
  - oaktown?
** NO endless car-centric suburbia..
  - *well, all of Cali except SF and downtown areas is this.. :/*
*** OKAY LA
  - *TEMP: i'm reconsidering that this may actually be better than berkeley, SD, and SJ..*
  - has *by far the best energy out of all of California, from SD to SF*
    - *generally livelier, happier, more energetic people, the opposite of stingy*
      - though, also *burnt out*
    - *generally, easier to get along with, sharing a suburban hustling 'n bustling culture.. similar to how the NYC hustle brings people together*
      - *including whites, latinos, blacks, a few asians.. everyone! :D*
        - *including first generation immigrants!!*.. truly everyone mingles
      - *honestly, feels like living in middle-class Virginia Beach nieghborhoods, but with more positive energy, industry, ethnic enclaves, etc..*
        - this could be fun..!
    - *has a larger variety of people, beyond the tech people of the Bay Area*
      - *attracts artists, especially performance artists*
      - *attracts first generation immigrants, whom are similarly lively!*, as there are significant existing ethnic enclaves
    - has that *too big to fail* energy
  - nightmare lack of urban planning and architecture
    - *really have to look beyond this to see the beauty of it: the people and their cultures*
    - actually results in far more comfortable, spacious living/lifestyle, befitting the weather
      - houses are more spacious, with more luxurious bathrooms, kitchens, etc.
      - *the people have a very suburban, comfortable lifestyle too*
  - *industry and culture sucks compared to NYC: just too fake, flaky, stupid (except LBC, south-central)*
    - possibly the center of woke culture
    - just far more complacent, simple-minded businesses without assimilation nor innovation
  - *might actually have the best weather in Cali..*, for sub-tropical people like me, asians, blacks, 'n latinos
    - *feels much warmer than san diego, with less wind, though still retaining a good ocean breeze* to clean the air
    - *can stay outside at night, nearly all year*
      - *can motorcycle/bike at night too*
        - actually easy and comfortable (weather) to drive at night, even by motorcycle.. feel calm, though people do speed through the night..
      - *perfect porch/patio weather*
  - *possibly has the greatest amount of affordable housing among the most sought out places to live in California*
    - *some places go for $650/month!!* (Carson)
    - quite a few places under $1000, which is far more rare in SD (all of it), Bay Area, and possibly Santa Cruz
    - *lower minimum wage, average wage, and professional wage, especially in tech*
**** *has by far the most amount of distinct neighborhoods, especially ethnic ones:*
    - *LA is a microcosm of California*
      - basically, the rest of SoCal, and even NorCal (except SF and SC), can be found in LA:
    - *but most suck: are exclusive, ethnic-based, traditional or class-based*, with LBC as one of the rare few exceptions:
***** YES *LBC*
- *the only thing good about LA..??*
- *oakland on the sea*
  - similar demographics: black, south-east asian, *pan-gender*
    - lots of young people, especially students
  - similarly ghetto: homeless, drugs, crime
    - though, possibly less crime than Oakland..
  - similar to east coast cities: philadelphia, baltimore
    - overshadowed by a nearby bigger city, port, black population, lively music 'n arts, etc.
- *a microcosm of LA, and therefore California*
  - a mix of good and rough areas, making it a prime place to start busineses, especially for the surrounding bedroom Asian neighborhoods:
    - those surrounding areas are not fun to live in.. best to stick to the LBC and retain community relations
    - westminster is old Vietnamese money/families, complete with old retired dudes playing chess at cafe/gambling dens
    - garden grove is old Korean money/families
      - all are sprawling, strip mall suburbs
    - carson has a Filipino population
    - chinese people seem to be all around too..
- long beach
  - can easily drive/bike/walk up to several parking lots right next to the beach, like ocean beach: simple satisfaction for the lazy, *i actually love it!*
    - lots of people playing black music! :D
  - *the air is much warmer and less windier than san diego, reminds me of Taipei!!*
  - *the water is much calmer*, thanks to it facing south, like a bay, *and it calms me down too :)*
  - can't swim here
    - *the LA river dumps out all it's shit here, and there's a huge harbor*
    - maybe okay to dip your feet in..?
- *terrible traffic in every direction*
  - thus, you are trapped in there..
    - but you don't want to be anywhere else anyway..
    - tough to get to north-west LA, and impossible(?) to get to north-east LA, however:
    - *has the blue line to downtown (can transfer at main station), north-east LA, SGV, etc.* in case of an event
      - just have to think of it as riding the Caltrain in the Bay Area.. it's a very very long-distance train..
      - frightening to go on the wrong time, but maybe alright on the weekends and during events..??
- has some more beaches nearby: seal beach, bolsa chica beach, then huntington beach (costs $15 to park..!)
- *possibly even better weather than oakland, as you get the ocean wind!*
- snoopy d o double-g
***** [?] west/ocean-side LA
- maybe too white.. rich white like san diego
- venice beach
  - like ocean beach
- santa monica
  - MAYBE *silicon beach*
    - *UCLA*
    - *the best campus and food*
      - *TODO: hmmm, maybe not a bad place to work.. i mean, if you're going to be on the campus everyday anyway..*
    - near hip hollywood, or homeless hollywood.. and burnt malibu/santa monica
      - interesting.. but seems to only be huge companies, not a startup hub like SF 'n NYC..?
***** [?] north-east LA
- like berkeley?
- looks quite boring... maybe too white..??
***** [?] pasadena/south-pasadena
- like palo alto?
- also looks too boring, with big boring financial company headquarters..
- adjacent to SGV
***** NO chinatown (in dtla)
- tiny, as in a few blocks..
***** NO downtown
- like san diego's: garbage
***** NO the rest of LA / endless suburbia
  - like south bay and asian suburban in san diego, but flatter, and seemingly more endless, as nature is further away
  - *endless tract houses 'n strip malls, welcome to car city*
****** NO north OC?
- vietnamese, koreans, filipinos, chinese, etc.
****** NO SGV
- *SGV scared me.. these are not the Asians i was lookin' for..*
- chinese, including taiwanese, suburbs
  - boring
****** NO SFV
- latino, white
  - equally boring, with less culture
******* NO the north of 210 along the foothills
  - *pasadena*, altadena (north of pas), sierra madre, monrovia (, bradbury, duarte), azusa, etc.
  - seems *really bland, overtly suburban, and over-priced*
    - crazy expensive for pasadena, high for monrovia, exclusive bradbury and duarte, just leaving sierra madre
    - all white
      - pasadena
       - 1-6% chinese/filipino/korean/indian/japanese
      - altadena
        - has/had a few black people, before the fire
      - monrovia
        - 7% chinese
      - azusa
        - only has 2% asians!
    - all have tiny little "downtowns", which is basically one street intersection with a few over-priced shops.. though, to their credit, it's better than a strip mall!
  - *access to the san gabriel mountains*
    - *brushfires come down from those mountain passes!*
  - a recent metro blue line extension now goes through it
    - but seems unnecessary, as most people that live in those areas drive cars, just bringing homeless people to their neighborhoods

******* OKAY just below the 210
  - south pasadena, san pasqual inc., san marino, east pasadena, east san gabriel, arcadia (stretches above the 210), mayflower village inc.(, irwindale)
    - south pasadena
      - chinese 14%, korean 7%, japanese 3%, filipino/vietnamese 2% each, other asians <1%
        - still good..
    - *arcadia and san marino are exceptional as they have good schools and attracted a large Taiwanese population*
      - YES arcadia
        - 41% chinese, 1-3% korean/taiwanese/filipino/indian/viet/jap/mixed
          - *incredible spread*
        - *arcadia hosts the 626 Taiwanese night markets* in the parking lot of their main park
      - san marino
        - low population density, completely residential zoned, large gated properties
        - 41% chinese, *5% taiwanese*, japanese/korean/filipino/mixed/indian 1-2%
      - san pasqual
        - above san marino
        - only 4% chinese/japanese, 3% taiwanese, 2% korean
      - YES east san gabriel
        - exceptional here having an abnormally high population density: 15k/sq. mile
        - 35% chinese, filipino/viet/jap/taiwan/mixed/korean/indo/indian 1-4%
          - *niiice spread!!*
    - irwindale is a place for mining, not living
  - *very expensive*, at least between south pas and san marino, still expensive from arcadia to mayflower village

******* YES above the 10, before the eastern 605 intersection
  - *alhambra, san gabriel (, northern part of rosemead?), temple city*, el monte, baldwin park
    - gets ghetto gangland starting from el monte
    - alhambra
      - chinese 35%, vietnamese 5%, filipino/mixed/japanese/taiwanese/korean/indonesian/cambodian 1% each
    - san gabriel
      - *chinese 43%*, vietnamese 6%, filipino/mixed 2% each, japanese/cambodian/korean/taiwanese 1% each
    - temple city
      - *chinese 43%*, vietnamese 4%, taiwanese 3%
    - rosemead
      - chinese 35%, vietnamese 14%
        - the most amount of vietnamese beyond the westminster enclave
    - el monte
      - chinese 17%, vietnamese 7%
  - *more dense, more street-feeling, authentic*
    - all have high population density at ~10k/sq. mile
  - *valley blvd is an endless strip mall of Asian businesses*
    - "On Valley Boulevard alone, there are around 200 restaurants"
    - is the *local route to south-east SGV* (instead of the 10)
  - main st. / las tunas has a good amount of strip mall businesses too
    - but it also has stetches of boring automobile dealerships
  - *can be on the same horizontal streets to north-east LA, with alhambra being a mere 5 miles away from highland park*
  - seems even more boring then its northern and southern neighbors, *without surrounding nature, in a concrete jungle*

******* YES below the 10, before the eastern 605 intersection
  - *monterey park, rosemead (north) / south san gabriel (south)*, south el monte (north) / whittier narrows (south) (.., west covina)
    - monterey park is asian dominant, then becomes *50/50 asian/latino* at rosemead and south san gabriel, then latino from south el monte onward
    - monterey park
      - *chinese 45%*, *japanese 6%*, vietnamese 5%, mixed/filipino/korean 2%, others <=1%
        - still quite great, though mostly cantonese from chinatown
    - south san gabriel
      - chinese 29%, vietnamese 8%, *japanese 7%*, mixed 5%, filipino 4%, *burmese 4%*
        - *incredible spread*
    - south el monte
      - chinese/vietnamese 6% each (80%+ latino)
  - can add another 5+ miles from north-east LA
  - closer / straight-shot to DTLA / east LA
    - probably a natural migration for the people from downtown chinatown
      - yep, 1970s
  - more highway access: 10 (to hollywood/101), 60 (to SM), 710 (to LB)
  - *E/yellow line ends on atlantic in nearby east LA*
  - garvey blvd, for the monterey park portion, but then quickly becomes latino

******* YES walnut valley area
  - walnut, hacienda heights, rowland heights, diamond bar (, chino hills, eastvale)
    - most of the shops are along colma blvd parallel to the highway in rowland heights
    - *possibly the best spread of asians i've seen..* save cerritos and irvine
    - YES rowland heights
      - chinese 35%, filipino/korean ~6%, taiwan/vietnamese 2%, indian/japanese 1%
      - the *main strip malls* are here, from mostly taiwanese/chinese mixed with viet/filipino/others to all-korean
    - OKAY hacienda heights
      - chinese 25%, *korean/taiwanese/japanese/filipino ~3% each*, other asians
      - likely okay, just being adjacent to rowland heights, and being on the same side of the valley
    - NO diamond bar
      - chinese 25%, korean 10%, filipino 7%, indian 4%, taiwanese 2%, vietnamese 1.5%, japanese 1%, others..
      - bigger housing, stores, parking lots, and therefore even more boring
    - NO walnut
      - chinese 34%, *filipino 15%*, taiwanese 3%, 1-3% a bunch of other asians
      - there isn't much on the north-side of the valley..
      - cool little valley roads running in-between the hills!
    - NO west covina
      - NOTE: also belongs to latino-land and below the 10 headings
      - chinese 10%, filipino 10%
        - probably the parts zoned within walnut school district
      - gets *nasty industrial* as it's near industry city
  - *many of the rich asians, including new immigrants, moved here*, from west SGV or their home-country
    - many work in nearby industrial-zone only city of industry
      - Taiwanese computer part manufacturing companies with shit work ethics and low wages
        - includes newegg.com!
      - 0% business taxes
      - more like a strip of warehouses next to the highway than a city
    - *after the western part of SGV, this is the second largest population of Asian Americans in LA, and possibly the US*
  - good schools
  - *too isolated and too far from the action of LA..*
    - you'd have to pass through miles of suburban hellscape to get anywhere
      - *limited to the 10* to get anywhere
    - likely creates more insular people too
  - *"the area is comparatively drier, hotter with worse air quality than the rest of LA"*
    - yet.. *i felt quite good up in the hills, and greener too!!*
      - awesome *windy canyon roads that remind of Asia!! :)*

****** [?] north-east LA
- east of the 5, north of the 10
- north of 101
  - atwater village, highland park, eagle rock, glassell park, cypress park, etc. (not glendale)
    - eagle rock has a good amount of filipinos, but many (likely newer generations) moved eastward
  - hipster, gentrified, white
    - *this area seems the quickest to change/gentrify*
      - *investors most likely making it over-priced*, like north park and berkeley
    - *can have some fun artists, musicians(?), DIY art organizations, hip businesses, etc.*
    - looks quite bland... maybe too white..?? might suffer from the same plight north park: lack of diversity, *lack of tradition*
    - "HLP on the other hand doesn't have a massive Asian demographic from what I've seen, is very densely populated, and from my experience has a much younger average age demographic. Depending on where you live in HLP it's much more walkable than Pedro or most of the South Bay, and there are *hundreds of local small businesses, cafés, bakeries, etc that you can easily frequent without having to drive*. If you don't live in an area of HLP that's nearby the shopping areas though and try to drive there, parking is pretty horrible. HLP also has the benefit of being *geographically close to places like Pasadena, Burbank, Glendale, DTLA, Arcadia, Monterey Park, Alhambra, etc*, though which all have areas with dense Asian communities, it'll just be more of a drive to them due to traffic density."
- south of 101
  - lincoln heights, rose hill, el sereno, etc.
    - maybe next to gentrify..??
      - "There is a reason why it's not developed. Need to bring major cash. City Planning and boe make it hard. Hillside grading and utilities make it hard."
****** NO east LA
- likely gentrifying, with new asians and whites moving in
  - though, very slowly, as *it's littered with industrial buildings, graffiti, old infrastructure, etc.*
    - it might be *the oldest district in LA!*
- latino
  - mostly working-class latinos live here
  - used to be gang heavy, still has some
- boyle heights
  - too close to DTLA
- lincoln heights, city terrace, montebello
- el sereno

****** NO gateway cities (except LBC and maybe cerritos)
- see LBC under small towns
- NO *cerritos/artesia + parts of la palma/bellflower
  - *the location seems trapped in the middle of nowhere: surrounded by gateway city land*
  - *a pocket of majority asian: a very rare great asian demographic spread*
    - filipino, korean, chinese (20-25% of asians), indian (12% of asians), japanese/taiwanese/vietnamese (2-5% of asians), others
      - a great amount of filipinos
      - possibly the most dense south-asians
        - has an *indian street*
          - with a few Taiwanese shops nearby!
    - ABC school district attracts asians
  - safer, police actually work
- bellflower, norwalk, downey, whittier, south gate
  - mostly latino-land, can get rough 'n rowdy, rather *indistinguishable, bland*
  - "Cerritos would be the top pick, followed by Artesia. *The only con is affordability.*

    Whittier is a personal favorite, but I think it skews Hispanic(?). The other side of the hill, and to the north, is where there are large Asian communities. Also, I wouldn't call it exactly freeway adjacent. Lovely town though.

    Bellflower is kind of meh. Some parts I'd consider the whole Cerritos/Artesia area, and others I consider more aligned with Long Beach/Lakewood. The same is going to go to Norwalk -- not really large enough or distinct enough to have it's own identity. Like, I'd live there, but I'd go other places to do stuff. However, I know quite a few people of South Asian and Pacific Islander decent that enjoy living in these towns."
    - https://www.reddit.com/r/MovingToLosAngeles/comments/1elmnfe/whittier_vs_norwalk_vs_cerritos_vs_downey_vs/
      - looking for safe, asian, etc.
  - "Cerritos all the way. It's full of Asians, Indians, Whites and Latinos. Safest out of all 4. No gangs out there except for posers. The cops actually give a damn and respond quickly to crimes. Quality of life is great.

    Long Beach is only feasible if you're able to afford a place on the very east part near the 605/OC border. But either way it's still Long beach so you're going to deal with quality of life issues the moment you venture out of your safe neighborhood. Useless slow cops, gangs, loud rap music blaring, mariachi music blaring, mobs of "teens" on bikes harassing people, etc.

    Bellflower and Norwalk are ghetto. Just yesterday they literally had a land a full on SWAT helicopter a residential public park in the middle of the day because of an armed robbery/homicide. There's also homeless people everywhere. Not much of Asian population to speak of except some small pockets.

    Downey is okay only if you're Latino/Mexican. The people there are kinda pretentious because they like to think they're above the "ghetto" surrounding cities but in reality they are not any different. They only hold that reputation because their small police department used to engage in civil rights violations and they would profile perceived gang members and drop them off in other cities. There is not really an Asian population in Downey."

****** NO north OC
- one or two-storey single-home houses with spacious yards sprawling all the way
  - notably *lacking small parks*.. *it's suffocating..*, though thankfully the beach air saves it
  - have to ride to hill trails or long/huntington beach
    - *long beach is such a great asset to have nearby!!*
- decrepit strip malls that could've belonged to any lower to middle-class neighborhood in VA Beach
- old traditional asian money: vietnamese, koreans, etc.
  - *this certain blend of people seem very insular, exclusive*
  - *but also has a great blend of asians on the northern parts, above the old korean/vietnamese neighborhoods*
  - https://www.reddit.com/r/orangecounty/comments/18g7gp8/where_the_asians_are_at_in_oc/
  - [?] the area northeast of buena park (buena park, fullerton, placentia?, brea, yorba linda)
    - [?] yorba linda
      - also a great asian spread
    - [?] brea
      - 1-6% korean, chinese, filipino, indian, vietnamese, japanese | <1% pakastani, cambodian, taiwanese, lao
        - wow..
    - [?] fullerton
      - 12% korean, 1-3% chinese/filipino/indian/viet
  - [?] buena park
    - koreans (10%) and filipinos (8%), some indians/viet/chinese too
  - NO cypress, la palma, stanton
    - a good asian spread, korean and filipino dominant
    - seems pretty bland, mixed up, with a few random latino and asian strip malls, then bland white burger joints
  - NO garden grove
    - 30% vietnamese
    - koreatown: old Korean money/families
      - centered on garden grove blvd
      - migrated to buena park
      - i've always found Korean culture to be boring as fuck
    - *has an old conservative racist white stronghold*
      - https://www.reddit.com/r/orangecounty/comments/1cfrub0/is_there_a_lot_of_racism_in_west_garden_grove/
      - kinda fits the xenophobic koreans, lol
  - NO westminster (+ midway city)
    - little saigon: old Vietnamese money/families, complete with old retired dudes playing chess at cafe/gambling dens and drinking at karaoke clubs
      - centered on bolsa ave
    - *has a similar comfort to Chinese surburban neighborhoods, containing all the shops you would ever need and could find in their home country, giving the feeling of their home country*
      - *actually seems great, it's just that the Vietnamese people are of an older, insular generation*, that it seems really difficult to get into
    - *tightly packed ethnic enclave, absolutely dominating the region's strip malls*
  - NO fountain valley
    - 30% vietnamese, a few of other asians (Chinese, Japanese, Taiwanese?, etc.)
    - park is a huge waste of space
  - many parts of OC have 10%+ asian
    - a good amount is still Chinese

****** NO south OC
- FUCK NO
- rich, *old money, conservative (including Trump)* asians (including Indian) and whites (40% each), and some latinos, some arab, some persian too, rare to *no blacks :(*
  - the "white asians", white-washed
    - asians mostly live on the northeast side, near the hills: northwood point, eastwood, orchard hills, etc. and great park too
    - this makess sense for Taiwanese people
- irvine
  - *majority 42% asian!*
  - a rather big county
    - *236k asians!*
- tustin
  - 22% asian
- many parts of OC have 10%+ asian
- *generally considered the most boring part of LA, and possibly California*
  - starbucks galore, 85 degrees cafes, clean, middle to upper class
    - the food sucks too, including the hipster crap, save costa mesa
    - *"The only fun to be had here is retail and chain restaurants."*
  - wide multi-lane streets
    - *frightening to me!!*
- *generally considered to have the most stuck up police/enforcement*, along with *strict HOA*
- "OC Asians have this kinda keep up with jones kinda life style. While SGV Asians are more about street life."
- UCI
  - shit campus, similar to UCSD
  - *highest amount of asians* out of all the UCs
****** NO SFV
- *the only thing worse than south OC*
- latino, white
  - *even more boring??* (is that possible!?), with less culture
- there's a few hip neighborhoods on the other-side of the hills above hollywood
  - but might be a problem if you commute to LA/NELA/etc.
  - studio city
  - panorama city
  - etc.

*** [?] san jose / south bay area
  - overall, i think i'd just prefer LA metro / SGV or cities (SF, NYC, etc.)..
    - NOTE: this is the last big metro to explore/travel
  - *only worth living here if you have a high-paying tech job nearby..*
  - *basically south OC but with solely tech bros, no girls, at all: man jose*
    - rich, boring asian tract-house suburbia
    - *literally nothing fun to do, no events*
      - have to go into Taiwan mode, and just socialize, talk, eat, drink, travel together :)
  - *no nightlife*
    - https://www.reddit.com/r/bayarea/comments/tiifqv/nightlife_bay_area_vs_socal/
      - basically, LA just attracts those into media/entertainment types, those that are outgoing, social
      - mostly families, not a destination for young people
      - just suburbs / bedroom communities, no downtowns
      - expensive to start such a business
        - maybe difficulty with permits, noise, etc.
        - population not really into going out (tech people) nor spending money
  - *food still doesn't compare to SGV*
    - https://www.reddit.com/r/FoodLosAngeles/comments/1bsw1qk/which_metro_area_has_better_chinese_food_los/
      - beyond SF (chinatown, richmond) a few Taiwanese spots in southbay (fremont, cupertino, etc.), it doesn't even come close to the SGV
  - at least people actually live here though.. compared to transient berkeley and SF..??
    - not a great thing, as i saw in the suburbs of san diego..
  - a useless downtown
  - *no beach..? what about mountains..? waterfalls? rivers??*
    - i think i'd feel trapped here..
  - *tech work / BIG TECH MONEY*
    - the boring, corporate kind.. (*startups are in SF, NYC, a little in LA/seattle*)
  - san jose
    - vietnamese dominant
  - *cupertino (and surrounding areas: saratoga, sunnyvale), santa clara, mountain view, foster city, milpitas, fremont, etc.*
    - *a lot of asians*
    - smellpitas: air from a nearby landfill wafts down
      - best asian spread
    - chinese and indian dominant split
    - *taiwanese tech scene*
      - see fb group posts

*** NO san diego
- *basically, a duller, mellow, less cultured (diversity and ways of living/thinking) LA with nicer beaches and cleaner, newer development*
  - *lacks the energies of: artist culture of LA, tech-startup culture of SF, and research culture of Berkeley 'n Stanford*
  - *the beach alone makes it much more livable than suburbs without beaches*
  - still $1000 minimum for a room in a house/apartment
- transient population
  - lots trying to move in, just as many getting out..?
  - lots living in RVs / cars in/nearby RV parks
- tourists
  - not so many..
  - they stick to the beaches though.. and bring in easy money!
  - and probably bring the prices up too..
- *chill surfer/skater/bohemian culture*
  - gets old.. *i prefer the energy of the city: NYC, and probably even LA todo
- *car-camping culture*
  - *RV camps, park next to beach, everything!*
  - *truly stress free*
- school (UCSD) is lame, STEM only..
  - the school's campus is also lame: modern 1960s office buildings, car-centric
  - kinda in the middle of rich areas: surrounded by the beach, torrey pines, la jolla, small hill/valley neighborhoods
  - *influenced/created biotech industry*
    - which is also lame..
- SDSU (SD state) is a party school, not competitive
- jobs pay less than LA and Bay Area, yet the price of housing is the same

**** neighborhoods
***** OKAY north park
  - *hip, young, lively, liberal, subruban-bikeable small town*
    - lots of indie shops 'n restaurants (and not in strip malls!!)
      - though, still quite strip-malley around hillcrest and a few other areas..
    - a little strange though, like a suburban neighborhood turned hot-spot, like berkeley..
      - still made for cars
    - still quite white.. though, a good amount of latinos from the east/south-east, and asian kids from the north too!
  - *perfect location*:
    - *in-between bedroom asian and latino neighborhoods*, where you can get real food.. though, it's all in *over-priced suburban strip malls..*
    - *close to ocean beach and mission/pacific beach!*
      - *yet far enough to avoid the cold, coastal weather*
  - *over-priced*, better to live in the asian or latino suburbs
***** NO ocean beach
    - *a small, dumpy, beloved beach-town of it's own..*
    - *like haight st., can get old quick*, though, still cool, as far as music performances go
    - very white
      - *i'm afraid, too white for me.. too mono-culture, too american*
      - *very exclusive neighborhood*
    - *the water is COLD*
    - very competitive housing
    - *very often has weird cold beach weather*
***** NO pacific beach
- *boardwalk/beach*
  - unaffordable to have anything cool on it
  - *still, just great to have tho.. everyone comes out to this one!!*
- neighborhood has all the major grocery stores
- *insecure frat boys, proud boys (racists), and military boys fighting*
***** the rest of san diego / suburbia
- *culture-less*, in diversity and ways of thinking/living
- *strip mall and white-painted SUV subrubs, like an extension of LA*
  - *new boring tract homes inland/north-east, and still a million minimum..*
- *no black people in most of San Diego??*
  - *this really kills the liveliness of SD..*
****** [?] latino neighborhoods
- *more diverse, including a few black and filipino enclaves (bay terrace)*
  - filipinos near 32nd st naval base in national city
****** OKAY asian neighborhoods
- LA prices for... what? the beach..?
- *VA Beach at 3-5x the price*
  - not the asians i'm interested in!!
    - *though, they do remind me of myself..: suburban, computer-oriented*
- a cooler/chiller/newer alternative to OC..?
  - but without the community, industry, creativity, etc., also much like VA beach
- *mira mesa feels like an asian virginia beach neighorhood*
  - *filipinos, vietnamese, indian*
    - lots of filipinos too!
      - next to miramar naval base
  - miramar has a little indian area thanks to qualcomm
  - convoy, just across miramar
    - which is where electronics manufacturers were, where japanese and koreans worked
- "National City -> Mira Mesa -> Penasquitos/Rancho Bernardo. Nowadays, it's Eastlake/Otay Ranch, I think?"
  - migration of filipinos (along with other asians)
- CV, poway, 4S, del mar
  - chinese and high-tech workers moved to these upper-class areas for the school districts
- linda vista
  - government built houses for vietnamese refugees
- the canyons and highways of San Diego make adjacent neighborhoods feel like a trek away, unlike LA
  - must cross miramar to get to north park
  - must cross a bunch of highways to get to the beach
  - must take the highway to go anywhere inland
****** NO north county
- *endless beaches, all bought up, owned by and live in by white people*
  - mostly rich white families (with businesses elsewhere?) with boats, SUVs, and other boy toys
- similar to west LA (manhattan/hermosa beach), but newer/later history
- oceanside
  - may be the exception, with *a great weekly street market* (biggers than ocean beach!)
    - maybe people from the inland areas come out for the hustle..
  - or maybe not, still appears to be bought up by investors, and *has a lot of big, ugly, hotels 'n apartment buildings..*

*** NO oakland
  - *??*
  - crime scared most people and economy away
    - including the long-enduring chinatown
  - seems for young, hip people.. too young 'n hip..
    - *provides a good counter-balance to berkeley, with street smarts*
    - k-town def for kids
    - lots of shops in downtown also cater to the hip youth
  - *black american culture*
  - actually good weather
  - beyond downtown is boring suburbs, without the ocean
    - dyin' of thirst
    - *fruitvale has a lot of latino people vending food out on parking lots!!*
      - maybe the start of latino-land..

* unliveable areas
  - basically, anything north of SF, as it gets more cold, cloudly, rainy: *depressing*, especially beyond the summer months
    - however, beautiful during the summer!
  - also, it becomes very white, as they are the only ones who can tolerate such miserable weather, and their own race / lack of other races
** portland
- rainy
  - *more rainy than seattle!?*
- cloudy
- white
  - really, *no asian communities!!*, but it makes sense for a city with public transport..
    - though, ~7% asian: 2% viet, 2% chinese, <=0.5% every other asian
  - culture-less
** seattle
- tech hub / bellavue
  - microsoft
  - tech asian community
    - probably like fremont
- university of washington
  - a legit public/state uni
- cloudy
  - *no sun for several months during the winter half*
- rainy
- white
  - though less white than portland.., thanks to the tech hub?
    - actually has *14% asians*!: 4% chinese, 2% filipino/vietnamese, 1% indian/japanese/korean, <=0.5% everyone else
      - also *has asian areas*: international district, little saigon, beacon hill, etc.
** most small towns of Cali
- just too isolating.. vacant of culture






* ride back up the coast
https://bestneighborhood.org/race-in-san-diego-ca/i
  - a great site to see the racial divide in America, and find liveable places amongst other minorities
  - all white along the coast, no minorities in north county
    - except a valley inland from oceanside: vista, san marcos, escondido
  - asians, mostly east asians, are stuck in the middle, upper-class suburbia in mira mesa, sorrento valley, etc. super boring. they go to convey to eat out
      - had a bad history with the chinese, with chinatown taken down for city renovations
  - tiny filipino population stuck in bay terraces, surrounded by latino nieghborhoods and the naval base
  - south and south-east is all latino! and a few black people
    - probably the only diverse place to live.. with low-income housing

LA
  - *most diverse, by far, makes San Diego look like a joke, until south Bay Area*
  - *long beach, only beach area that's not white (black, latino, and south-east asian!)*
  - asians in:
    - notably divided by race
    - san gabriel, rowland heights/diamond bar hills, eastvale
      - FAR from everything!.. but they built their own world, i guess...??
    - *OC: irvine, viet in garden grove and westminister, artesia, NE of buena park*
      - *access to the better beaches, LBC, and DTLA. not bad..*

*oxnard*
  - latino
    - try it out..?

no asian until near UCSB

santa maria
  - latino

SLO
  - all white

hwy 101: soledad, salinas
  - all latinos

*watsonville*
  - all latino
  - good stop before santa cruz..

bay area
  - san jose, fremont, hayward, tri-valley
  - vallejo

sacramento
  - south of sac, in elk grove

NOTHING UNTIL SEATTLE
  - a few sprinkles in portland, but likely too gloomy, rainy for most asians






* random research
** reddit tidbits
https://www.reddit.com/r/aznidentity/comments/vjg4h6/some_observations_about_the_bay_area_from_an_la/
  - hmmmm, super interesting sub-reddit


an interesting bit on LA history..:

Just to put the SGV into perspective. Housing segregation was still a thing well into the 1980s. In many SGV ghetto areas, it was 5% to 10% Asian in the late 19th and early 20th century (and majority Mexican), when it was more agricultural. They lived in work camps at first, as contract labor. These camps became ghettos. So the area was prepped to become the SGV it is today, because of these seed communities.

Read this: https://imdiversity.com/villages/asian/history-of-asians-in-the-san-gabriel-valley/

That's also why the SGV was never really fully white. Nor was it ever fully considered "LA", because it was never able to wipe out these old Mexican and Asian populations. Also, some of the original whites into the area, like Temple and Workman, sided with Mexico in the Mexican-American war, and bailed out after the war.

You don't see all these roots anymore, because a lot of the people were Japanese, and put into the concentration camps during WW2, and the communities were wiped out. Also, there were Chinese camps, and towns, and those got burnt or buried. There was also a Korean town, I think, in the Inland Empire, and that's also gone.

Also, Chinese have been in the City of LA since the 1850s. By 1870s, there was a Chinatown of around 200 people. Then there was the massacre. Later, that small Chinatown was wiped out by the train station and freeway.





It is related to the % Whites in neighborhoods.

The most un-Asian/white-washed/self-hatred places are all the suburbs over 80% Whites.

The most AZN places are somewhere like Honolulu (16% Whites) , enclaves in and around LA ( Monterey Park 4% Whites) , and enclaves in NYC ( Sunset Park 10%, Flushing 9%)

Let me make it clear, it's not about % of Asians, but % of Whites.

Places like Irvine, West Bay, Seattle, Vancouver, despite with large Asian population, are very different from Honolulu or LA ( at least currently) . Because the % of Whites is still very large.
