
ordered

*santa cruz*
  - *ocean AND mountains!!*
    - *redwood forests*
  - *most rad, by far*
  - *arts department has masters' classes for all of my interests:*
    - MFA in film
      - MFA in social documentary
    - MS in playable media and games
      - part of theater department
    - MFA digital arts and new media
    - B? in creativ tech
      - the first
    - MFA in environmental art and social practice
    - PhD in film and digital media
    - also MA/PhD in philosophy and history, including a PhD in feminist studies
  - chill surfer/skater/bohemian culture
  - the tech people that love nature probably came here first
    
davis
  - maybe more affordable?
  - *school is bikeable from town*
  - *entire school is bikeable*
  - agriculture, vetrinary
    - agriculture =/= permaculture
  - has the only design major, undergrad and grad
    - looks lame though..
  - well-praised school

SF
  - *startup culture*
    - now ai :/
  - noisebridge
  - asians!
    - but no black people :(
  - ocean sucks
  - good small parks culture
  - golden gate park and city events
  - good sense of neighborhoods
  - city college
    - *FREE SCHOOL*
  - CCA
    - meh, nothing in Cali compares to NY's arts culture..
  - UCSF
    - just medicine
      
  goleta/ucsb
  - just the school/college-town, actual town is useless
  - expensive area
  - *school is on the beach!*
    
san diego
  - school is lame, STEM only..
    - it's also really ugly, car-centric
  - ocean beach
    - can get old quick, though, still cool
    - very white
  - north park
    - asian restaurants!
    - closer to outer latino neighborhoods
  - endless beaches
    - all bought up
  - transient population
  - lots of tourists
  - chill surfer/skater/bohemian culture
  - car-camping culture

berkeley
  - the school's design department seems lame..
  - boring AF
  - mostly transient, half international students
  - no ocean, just the bay
    - not even close to the same vibe!!
    
san jose
  - ??


 
* ride back up the coast
https://bestneighborhood.org/race-in-san-diego-ca/i
  - a great site to see the racial divide in America, and find liveable places amongst other minorities
  - all white along the coast, no minorities in north county
    - except a valley inland from oceanside: vista, san marcos, escondido
  - asians, mostly east asians, are stuck in the middle, upper-class suburbia in mira mesa, sorrento valley, etc. super boring. they go to convey to eat out
      - had a bad history with the chinese, with chinatown taken down for city renovations
  - tiny filipino population stuck in bay terraces, surrounded by latino nieghborhoods and the naval base
  - south and south-east is all latino! and a few black people
    - probably the only diverse place to live.. with low-income housing

LA
  - *most diverse, by far, makes San Diego look like a joke, until south Bay Area*
  - *long beach, only beach area that's not white (black, latino, and south-east asian!)*
  - asians in:
    - notably divided by race
    - san gabriel, rowland heights/diamond bar hills, eastvale
      - FAR from everything!.. but they built their own world, i guess...??
    - *OC: irvine, viet in garden grove and westminister, artesia, NE of buena park*
      - *access to the better beaches, LBC, and DTLA. not bad..*

*oxnard*
  - latino
    - try it out..?

no asian until near UCSB

santa maria
  - latino

SLO
  - all white

hwy 101: soledad, salinas
  - all latinos

*watsonville*
  - all latino
  - good stop before santa cruz..

bay area
  - san jose, fremont, hayward, tri-valley
  - vallejo

sacramento
  - south of sac, in elk grove

NOTHING UNTIL SEATTLE
  - a few sprinkles in portland, but likely too gloomy, rainy for most asians






* random research


** reddit tidbits
https://www.reddit.com/r/aznidentity/comments/vjg4h6/some_observations_about_the_bay_area_from_an_la/
  - hmmmm, super interesting sub-reddit


an interesting bit on LA history..:

Just to put the SGV into perspective. Housing segregation was still a thing well into the 1980s. In many SGV ghetto areas, it was 5% to 10% Asian in the late 19th and early 20th century (and majority Mexican), when it was more agricultural. They lived in work camps at first, as contract labor. These camps became ghettos. So the area was prepped to become the SGV it is today, because of these seed communities.

Read this: https://imdiversity.com/villages/asian/history-of-asians-in-the-san-gabriel-valley/

That's also why the SGV was never really fully white. Nor was it ever fully considered "LA", because it was never able to wipe out these old Mexican and Asian populations. Also, some of the original whites into the area, like Temple and Workman, sided with Mexico in the Mexican-American war, and bailed out after the war.

You don't see all these roots anymore, because a lot of the people were Japanese, and put into the concentration camps during WW2, and the communities were wiped out. Also, there were Chinese camps, and towns, and those got burnt or buried. There was also a Korean town, I think, in the Inland Empire, and that's also gone.

Also, Chinese have been in the City of LA since the 1850s. By 1870s, there was a Chinatown of around 200 people. Then there was the massacre. Later, that small Chinatown was wiped out by the train station and freeway.





It is related to the % Whites in neighborhoods.

The most un-Asian/white-washed/self-hatred places are all the suburbs over 80% Whites.

The most AZN places are somewhere like Honolulu (16% Whites) , enclaves in and around LA ( Monterey Park 4% Whites) , and enclaves in NYC ( Sunset Park 10%, Flushing 9%)

Let me make it clear, it's not about % of Asians, but % of Whites.

Places like Irvine, West Bay, Seattle, Vancouver, despite with large Asian population, are very different from Honolulu or LA ( at least currently) . Because the % of Whites is still very large.
