
this serves as a todo list during travel using/learning the ways of (doom) emacs



1. apply to a few jobs via otta.com
2. head to SB
   - thursday, or whenever it warms up again
   

TODO: main
  - a numbered todo list seems nice... priority is good. can only do so much at a time
0. unemployment
1. motorcycle insurance
  - try all big names:
   - progressive
n. map out next hostel/place to stay
2. banks
3. update addresses
  - use 1520 Harmon St. temporarily vs parent's address
  - DMV site
  - banks
    - Charles Schwab
  - work
    - UCB



* TEMP reply to reddit (no internet)
https://www.reddit.com/r/SameGrassButGreener/comments/1bunybh/do_people_exaggerate_the_problems_california_has/
this is the best answer, from my time in Cali post-covid. The only way to do Cali is to have a traveler's perspective, take the van route, save dough, explore nature, and gtfo.
in addition to this, i think the economy is very tight here. Silicon Valley, where you must be a senior computer person. Ethnoburbs, where you must be of a certain race (yikes..!! LA is a village, lmao). Public higher ed is overtly competitive (ucb, ucla, ucsd, ucsb..) for both students and workers, competing against the rest of the world.

the (sub)urban development sucks too: two metro-burbs, only one walkable city, a few college-towns/areas (many not walkable!!), with little else in-between.



* notes (read before getting lost)

NOTE: merged from [job-search-uni-cali]

** goals
what's the game plan? *work during school year, go to parent's home or Taiwan during the summers/winters?*
  - *as long as i can make it back to Taiwan once/year, i think i can survive.. maybe.. i'm dying.. ;(*

whats the goal money? 5 years = 100k * 5 * 70%? = 70k * 5 = 350k
  - or *as long as i can do it?*
  - *TODO: is there a minimum for retirement?*

*at the same time, build tea business out of a van*
  - test income/time for that
  - can try in different towns/cities/campuses in America

try different jobs
  - *CONCLUSION: nahhh, in too deep to taking care of a chill space and/or computer-programming-related work*
  - *electrician*: hvac
    - 4 year apprenticeship ;(
      - though, you do get paid while doing it.. so it's a job + training
        - TODO: how much while an apprentice?
    - safety officer?
      - sounds like it combines EMT and just cares about the construction workers
      - https://www.reddit.com/r/Construction/comments/10uia8o/becoming_a_safety_guy/
        - "just sit down and watch others work"
        - a much hated on job
        - lots of paper-work
        - not better pay than an apprentice
    - https://www.reddit.com/r/IBEW/comments/15mvcn9/considering_firefighting_or_electrician/
        - "We don't get to slide down poles and nobody thanks us for shit. We usually don't get to wear cool PPE. They make better chili and we don't have a sexy electrician calander.

          But We rarely deal with fires and if we do we aren't expected to put them out. Our skill set is very useful at home and translates well to other careers if we decide to switch it up. We make way better money. We don't have to deal with the public very much. We can, on average, out drink any city employees. *If you like meeting a wide range of characters we got you covered*. I've worked with far right conspiracy theorists, former NFL players, punk communists, military veterans, felons, former strippers, immigrants from several different countries, just every kind of person who has a good story to tell really. *We don't have to walk in to the same building every day for years on end. The job is always changing. New locations and new areas. We get to see some cool shit.* Inside of nukes and power houses. Interesting factories and plants. You can cuss out your superiors and you might not get fired for it. Honestly I can't see myself being able to work any other kind of job again. Keeps interesting. Always new problems and tasks. *And if you don't mind traveling the whole country is open to you.*"
        - "Pros and cons to both and they’re very different so it’s hard to compare.

          Fire has long shifts and arguably more dangerous working conditions, but consistent pay and lots of time off. Seen as much more of a ‘prestige’ job than construction worker if that matters to you, although day-to-day tasks are closer to a labourer lol. Early retirement if you start young, but it’s very physically demanding and you’re basically living with a bunch of roommates for half your life which isn’t for everyone. Usually tied to one location your entire career.

          Electrical trade is absolutely huge (and growing) so it’s possible to keep learning new things your entire career, or simply find a niche that interests you and stick with that. Can be very physically and/or mentally demanding (or not) depending on the work you’re doing. Opportunities to travel the country and even the world if you find the right niche. Union pay & benefits is comparable to fire, but construction is inherently cyclical so there may be times when work is slow. Can even start your own business and the sky’s the limit.

          A lot of firefighters around here actually have a trades background & it’s seen as desirable when they recruit (always good to know how buildings are put together when you’re stumbling through them in the smoke)."
  - x/emt -> para-medic
    - https://www.reddit.com/r/electricians/comments/15ig035/you_cant_make_this_shit_up/
      - "*As a first responder, do not leave this trade for a first responder career. It pays like ass and is not as rewarding as you would think.*"
        - "Yeah lol I came here FROM first responder. This is much less stressful and pays better on average"
        - "same here. medic for 13 years and hit a ceiling with pay. you either go back to school for nursing or a PA or remain a lifer because you love the stress of bleeding ulcers and wondering if your gonna pull up on a wrecked car full of kids. mad props to those who do it day in and day out. after making the switch now i'm just in awe of how relaxing this trade is for me. therapeutic even."
  - x/firefighter
    - only 3-6 month training!
      - https://www.reddit.com/r/SantaBarbara/comments/1ehoa12/how_to_become_a_firefighter_in_santa_barbara/
    - but, it seems, both wildlands and structure fire-fighting, *will wreck the body: knee/hip/back/shoulder/arm pain, smoke/cancers, etc.*
      - https://www.reddit.com/r/Wildfire/comments/1lgftje/how_has_wildland_firefighting_changed_your_life/
        - people share their experiences in a single comment
        - "First it gave, then it took, so I left"
          - most people seem to do it to make some money, only to move on to a better job
        - bad gov support, no disabilities / benefits
        - *in general, just seems like a shit-show, being governed/run by idiots, military idiots, without being careful nor caring, just like any other government instutition: it just cannot compare to people taking care of themselves*
  - *i'm afriad both of these jobs don't provide enough freedom for me..* better to go the indie food 'n drink vending route.. combined with tech (startup, remote, self-maker)

*at the same time, find a home in America*
  - *likely a city with lively artists, doing it now*
  - *vend tea there!*

*at the same time, figure out a remote job (customer support + support dev -> systems dev / devops / sre)*

*at the same time, master making digital stuff (games, web apps, etc.)*


*during breaks, build a home in Taiwan* (primitive and mobile)
  - *and in America, build a mobile home*



** other notes
maybe better choosing a place first.. LA (city) vs SB/ucsb vs SC (+ucsc) vs another state , *building a GRASSROOTS community* there, then getting work through personal network..
  - *logically, no college-town has grassroots* (it's roots are the state or private institution)
    - *this just leaves santa cruz and la unis (ucla, usc)*, slo/cal poly, and davis (?? was davis a town before the school??)
  - *art scenes ARE a network of grassroots orgs*
    - thus, *cities with art scenes, with artists, ready to do stuff, together!*
      - *beyond that, there is nothing*

hmmm...
  - in this regard, *NYC was so much easier to jump into..* get involved.. so much more pro-active ("intentional") *more grassroots/DIY*, and all located within the same city, all accessible by subway..
    - *THE CITY IS THE SCHOOL*
      - similarly, *TAIWAN IS THE SCHOOL*
        - *REALITY IS THE SCHOOL*, but *in an area that's communal*

*DO NOT work during the summer, especially if it's just a college-town: it's boring as fuck*
  - (though i wouldn't mind santa cruz nor santa barbara during the summer..)

*check for jobs weekly*
  - *jobs are added nearly every-day starting from around the time that school starts (~august/september)*

*big research unis probably have the most job listings and turnovers*

*BEWARE: cannot update application once sent!!*
  - (except stanford)
  - for UCs, i think can withdraw and re-submit, as long as it's before the initial review date (IRD)
  - *take time to fill in relevant past work experiences*
  - when writing the cover letter:
    *list experiences that show you have the qualifications / ability to do the job*

see [masters-schools] for programs i'm interested in at each school
  - *TODO: this is a really good way to go.. and build a career, in both pro work (higher ed software work) and specialization (games, digital media, new media, etc.)*



https://www.reddit.com/r/ApplyingToCollege/comments/1b7571c/what_universities_actually_have_happy_students/


https://www.niche.com/colleges/search/best-colleges/s/california/

jobs.universityofcalifornia.edu



