

* stages
read-time
  - TODO: the user reading??
compile-time
run-time


* possibilities


http://www.paulgraham.com/diff.html
  - 9. The whole language always available. There is no real distinction between read-time, compile-time, and runtime. You can compile or run code while reading, read or run code while compiling, and read or compile code at runtime.

  - Running code at read-time lets users reprogram Lisp's syntax; running code at compile-time is the basis of macros; compiling at runtime is the basis of Lisp's use as an extension language in programs like Emacs; and reading at runtime enables programs to communicate using s-expressions...


  
during read-time
  - compile -> ??
  - run -> change syntax
    - may be able to change the language's syntax..
    - dsl?
  
during compile-time
  - read -> static analysis, static type-checking
  - run -> execute macros
    - "running code at compile-time is the basis of macros"
  
during run-time
  - read -> programs communicate (lisp), various dynamic featres (see below), dynamic/run-time type-checking
    - TODO: in the case of lisp, because it's syntax is so simple (a list of s-expressions), programs can communicate..??
  - compile -> eval / program extensions
    - run new code while the programming is running
      - includes adding code into the running program (data, functions, etc.)


* pop features

** all of the time?
(todo: wip)

eval
  - Some dynamic languages offer an eval function. This function takes a string parameter containing code in the language and executes it. If this code stands for an expression, the resulting value is returned... (vs higher-order functions)

object runtime alteration
  - A type or object system can typically be modified during runtime in a dynamic language. This can mean generating new objects from a runtime definition or based on mixins of existing types or objects. This can also refer to changing the inheritance or type tree, and thus altering the way that existing types behave (especially with respect to the invocation of methods).
    - mixin
    - metaclass

type inference
  - As a lot of dynamic languages come with a dynamic type system, runtime inference of types based on values for internal interpretation marks a common task. As value types may change throughout interpretation, it is regularly used upon performing atomic operations.

variable memory allocation (-> dynamic typing)
  - Static programming languages (possibly indirectly) require developers to define the size of utilized memory before compilation (unless working around with pointer logic). Consistent with object runtime alteration, dynamic languages implicitly need to (re-)allocate memory based on program individual operations.



** during read-time

(empty)

** during compile-time (and run-time?)
macros
  - ...combines code introspection (the ability to examine classes, functions, and keywords to know what they are, what they do and what they know) and eval in a feature called macros... they provide access to the inner workings of the compiler, and full access to the interpreter, virtual machine, or runtime, *allowing the definition of language-like constructs which can optimize code or modify the syntax or grammar of the language.*

Assembly, C, C++, early Java, and Fortran do not generally fit into this category.

*note: c/c++ people use the word macros for simple preprocessor-like substitutions/replacements*
  - though, this itself can be quite powerful.. with pieces of expressions or var/symbol names

reflection
  - TODO: different from run-time introspection?
  - ...common in many dynamic languages, and typically involves analysis of the types and metadata of generic or polymorphic data. (to macros?: It can, however, also include full evaluation and modification of a program's code as data, such as the features that Lisp provides in analyzing S-expressions.)


** during run-time

introspection
  - peer into the program
    - see all objects (and objects' relations), data, functions

program extensions
  - ??
  
programs communicate
  - !?!? the matrix?


