

* notes

** dynamic lang functions
*NOTE: this probably works with many languages with dynamic runtimes*
  - *including ruby!!*

spc-o-r
  - +eval/open-repl-other-window
    - don't bother with editing within the repl window, terminal windows have funky input..
  - only need this to start it, then can use eval functions

run the entire program in repl
  - then can run any function, like pry..??

run (eval) regions of code
  - spc-k-e (spc-e in meow)
    - +eval/buffer-or-region

send regions of code, functions, etc. to a repl
  - then can run functions, macros, etc.
  - spc-k-s
    - +eval/send-region-to-repl
  - spc-c-??

** explore lisp programs (emacs) dynamically
  - spc-l-g
    - filtered-search through all libs, functions, vars
  - m-x seems to be a subset of those functions.. (33k vs 7k)

** emacs notes
eventually, you'll probably naturally read enough lisp code when using emacs
  - spc-f-e
    - find file in ~/.emacs.d
      - TODO: .doommodule is the compiled file..? i can't seem to find the functions for dired..

c-(
  - auto-add parens in the right place
  - if you have paraedit
m-(
  - if you don't?

** lisp lang notes

(defun ra/post-config ())
  - can use / in the name? for name-spacing?
  - requires (), even if empty :/


 ;; TODO: wtf is with these elisp comments?
 ;; one ; confuses the formatter
 ;; two ;; seems the way to go..

*** symbols

people generally use setq over set, for the convenience, as it is what is expected coming from other languages
  - the q stands for quoted, and you don't need to quote (') the var
  - exception: if the value is another symbol (not a literal), you can use set to set it to another symbol

https://www.reddit.com/r/emacs/comments/7jyv0o/whats_the_difference_in_setq_and_set/

lisp has “symbol” concept.

in “normal” languages like python php perl java etc, they have “identifiers”.

in lisp, these “identifiers” are “symbols”. The difference is that, the lisp identifier can be evaluated or stay unevaluated.

if symbols are always evaluated, they are just like identifiers in other non-symbol language.

but in lisp, identifier can be held unevaluated. When identifier is held unevaluated, it becomes an inert thing, somewhat like a string.

(setq x 1)

(message "%s" x) ; prints "1"

(message "%s" 'x ) ; prints "x"
;; this is printing the symbol itself
;; that is, the identifier x is unevaluated

To hold evaluation of a identifier, you “quote” it. Like this:

'x

(quote x)

Normally, you write

(set 'x 1)

meaning, you set 1 to the identifier x. You want to quote the symbol, because, otherwise, x will be evaluated, but that usually doesn't make sense, unless its value is another symbol.

while

(setq x 1)
will quote the 1st arg, the x, for you automatically.



* install lisp:
scoop install sbcl

* install a lispy editor:

helix
  - (coming soon..)
  - scheme scripting

emacs
  - yay!

lem
  - an editor completely written in common lisp!
  - has several front-ends: ncurses, sdl2, etc.
  - https://github.com/lem-project/lem
  - learn to use it!
    - https://lem-project.github.io/usage/usage/

x/portacle
  - an emacs config specialized for common lisp
    - meh, i already learned doom-meow-emacs..
  - https://portacle.github.io/
  - scoop install win-portacle
    - "couldn't find manifest"

* learning resources:

https://github.com/GustavBertram/awesome-common-lisp-learning
  - *lisp koans*
    - https://github.com/google/lisp-koans

*land of lisp*
  - an old book that *teaches lisp by making games (or pieces of games..)*, in that cute old way when people took the time to write books well

*let over lambda*
  - a book about macros!
  - https://letoverlambda.com/
    - first 6 chapters are online, maybe in the process of being uploaded..??

https://gigamonkeys.com/book/
  - practical common lisp, formmated for digital viewing
  - not bad for a reference book..

on lisp
  - bottom-up programming, including functional programming, rapid prototyping, interactive development, embedded languages, and CLOS

https://github.com/rabbibotton/clog/blob/main/LEARN.md
  - learn by using CLOG, a gui that uses the browser as it's engine??
  - sounds like good immediate feedback..
  - it has a lot of examples and tutorials, but i'd rather stick ot the std lib


