
# see windows-cli.txt

# notes here are related to solely the language itself

# performance is extremely slow and requires optimization, scripts taking several hours before certain optimizations / understanding how it works, whereas ruby/python/etc. have optimizations built in the parser, thus, you'd have to be more careful writing anything cpu-intensive in this

# https://www.reddit.com/r/PowerShell/comments/owsk8b/comment/h7id09k/
# expensive things
#  - static method over function calls
#  - write-host
#  - pipelines
#  - etc.

# naming conventions
# seems to be case insensitive, which is great as .net uses CamelCase heavily
# doesn't like '-', or any special characters except '_'
# don't end folder paths with \
#  $home\my-stuff otherwise it would be $homemy-stuff
#  cp $profile "$configs\powershell\" throws an error

# run it / import it
. .\backup_configs.ps1
import-module .\install_apps.psm1

# environment vars
ls $env:
$env:psmodulepath -split (';')

$profile # path to powershell settings profile




new-item/ni my-file.txt







# learn x in y minutes
ls # can simply run a command like this!
$package_manager install $name # string interpolation on the command-name/cmdlet doesn't work

# another way to run a command (and more expressions?)
$cmd = "$package_manager install $name"
invoke-expression $cmd # TODO: any differences?


if (!(Test-Path $path)) { # or -not
    # note: requires () and {}
}
$array = @("stuff");
$array[0]

$hash = @{key = "value"}
$hash['key']

"string substitution is as easy as $string"

"string interpolation: $($array[0]) $($hash['key'])"

winget list | select-string "some-app" # pipe 'n grep
$string -match "regex" # pattern match operater (when not piping)

# optional typing / type-inference?
# default values for parameters
function install_app($name_or_id, [string]$package_manager = "scoop") {

}

# a more advanced way of describing parameters
function install_app2() {
    # generated by a vscode snippet: param-block-advanced-function
    [CmdletBinding()]
    param (
        [Parameter()]
        [TypeName]
        $ParameterName
    )
}

function simple { } # () is optional
simple # () is optional??, ruby-esque!


# put this at the end of a "module" (.psm1)
export-modulemember -function * -alias * -variable *

# check output properties of an object
this-function-outputs-an-object | get-member
or-this-way | select
$profile | select-object * # even env vars are just objects

# then select the object's properties/columns you want to output
some-function | select name, definition, description

# properties and values? TODO
or-this | format-list property *


