
NOTE: this file serves as a play-ground for org-mode


slowly but surely, emacs and i are becoming one..

one million glorious lines of text-based power~~!!!


BEWARE: WATCH OUT FOR THE WORMHOLE THAT IS EMACS
USE FOCUS EDITOR INSTEAD


some readings..
  - land of lisp, little schemer, K&R, structure and interpretation of compilers


* praise from matz

- https://news.ycombinator.com/item?id=6094610
  - matz made a powerpoint on emacs?? gotta love him!
    - 1988
  - emacs made me realize anything can be changed by a programmer, it is total freedom
    - i could edit without thinking key-binding
    - *i wrote my own email client, in emacs lisp. it was my first non-trivial lisp program. i used it everyday.*
    - 1993
      - started ruby
        - from emacs, it uses integers as pointers, mark and sweep gc, similar object model, then a smalltalk-like oo system on top. For syntax, i wanted a algol/ada/eiffel-like one.
        - but as an emacs-addict, i needed a langauge mode... *if i couldn't make ruby-mode to work, the syntax of ruby would've changed*
          - *TODO: did matz write ruby-mode??*


* sources
tips, tutorials, help:
https://github.com/emacs-tw/awesome-emacs#tutorials
discord
discourse
zaiste video series


configs of great programmers:
https://gist.github.com/amirrajan/b3e4af5e06ad46e1b390aae2d0a44e47


* config

*NOTE: DON'T YOU EVER USE IT AS ADMIN/SUDO!*

see [config.el] for notes on config
  - self-document!

*NOTE: first set up the right font and font size, it makes a big big difference!!*
  - can see a lot more in the mini-buffer!!
  - set font in terminal app settings or in doom's config.el


* (g)ui design

current setup:
treemacs
centaur-tabs
  - testing.. quite nice thus far..
    - works well with windows and projects, reducing the tabs related to the project (if not, cwd?) of the current buffer, and to that window
  - maybe have to wean myself off of this over time..

    
dired vs tree plugin
ibuffer vs tree plugin
  - tree plugins are far more compact, visual, enabling one to grasp far more info far more quickly
  - dired and ibuffer both take up a whole page-sized buffer, and has their own esoteric bindings..
  - ibuffer, with doom's "ibuffer" plugin enabled, does however display all buffers together, categorized by project..

minimap (de-map)
  - felt useless..
    - maybe okay if you have spare screen space..
  - people seem to use this as a replacement for the scroll bar, which is likely turned off by default..
  
if working quickly, just do quicksave/quickload (on doom's splash screen)
  - quitting doom emacs does this by default
  - at times, may need to save workspace session to a file (spc q s) 

  
TODO: projects vs workspaces vs persp(ective)

TODO: centaur-tabs vs native tab-bar-mode and tab-line-mode

** language specific dev
*** ruby
the localleader map (c-c l) is really neat 'n simple

it has the following functions:

robe-start
  - if there's no project, may ask you to run inf-ruby, an inferior ruby process. from then on, i think it's the normal dynamic lang run-time dev experience, similar to elisp: send code into the run-time/process, introspect it, etc.
    - may run into problems loading libs/gems in correctly.. as there is no project / (gem) bundler setup..
  - the process will provide a repl console: irb
    - irb itself is it's own thing.. providing a cli to do a lot of things..
      - if you don't bundle the project, and just want to try running some script, use irb to load libs..??

robe-doc
  - introspects the running process for docs, so you are reading the docs in the code, not from some seperate external source
    - maybe that's why they say emacs is "self-documenting"..
  - how does it differ from irb's show_doc?
    - it makes use of emacs search engine mini-buffer, making it a far better experience than irb

c-c l s
  - send code key-map
  - can send a require gem statement

c-c k
  - i don't think robe module uses the lsp..
  
(irb)
  - introspect objects (run methods), debug, load files/libs, etc.
  - introspection explorer portion mimics cli commands: ls, cd

(completion)
  - pressing tab works, but functions aren't ordered.. :/
    - TODO: fix this..??
    - may have to try zed after all..
    - or maybe a lsp module for ruby??
*** lisp

see [lisp.org]

parinfer (> paredit?)
  - handles parenthesis for you

lispy
  - modal bindings


* bindings
** a few quick ways to learn, interactively via run-time introspection:

learn x in y minutes / emacs


*find-function (c-h f)*
  - NOTE: contains all functions, and thus differs from m-x
    - 30k vs 7k functions
      
*find-var (c-h v)*


f12
  - gui menu
    - sometimes shows bindings for the menu item/command
    - TODO: how is this created..?

c-c
  - for major modes

*c-h b* / spc h b
  - b
    - all bindings
  - m
    - a better view of key-bindings quicker to undertand key-bindings than h-m..!
  - i
    - minor modes

c-h m
  - describe-mode
    - TODO: can't find this in the meow bindings..?
    - replaced by main info-emacs-manual
      - TODO: i might prefer it bound to h instead..

spc-h-M
  - doom/describe-active-minor-mode

[movement-command],[number]
  - repeat movement

emacs/meow philosophy
  - TODO: though, could add F for reverse find
    - no built-in function..? maybe emacs prefers moving forward only..?
  - helix used shift as a reverse modifier, i don't think emacs uses that idea..

** TODO some useful functions (to bind?)

most likely they exist somewhere, just gotta find it..
  - c-h b b

m-x cd
  - change working dir
    - useful to limit for find file


** TODO some useful bindings

command+click
  - *pop-up buffer menu, categorized!!*
    - WTF!?

meta-click
  - mouse-secondary-save-then-kill
    - kinda like G/grab..

spc-spc (c-spc)
  - set-mark-command
    - TODO: this must be important..??

m-x / spc-m-x (meow), : (evil)
  - contains every function available (~7500 with default doom install, ~6750 with meow instead of evil key-bindings)
  - usually [module]-[function]

[[cmd:recenter-top-bottom][c-l]]
  - center, top, bottom
    - *super useful*, never used this feature in another editor..

m-s-right/left
  - move list indents
  - hmmm, didn't know m-s was ever used..!

c-s/c-r
  - isearch forward/reverse
    - TODO: redundant, could use shift instead

c-h f/v
describe-function
describe-var


some notes:
 - NOTE: it's still vi, so still need to re-map caps lock to escape
 - NOTE: f1-key is tough on a chromebook keyboard, but quite useful!

*** meow bindings

TODO: finish [[fn:meow-tutor][meow-tutor]]

** key bindings (actual keyboard keys)

TODO: PENDING: merge from my [helix] and [wezterm bindings]
  - see [config.el]

notably emacs shares it's key-bindings with bash, nano, and most editors, all the way up to contemporary vs-code, helix (insert-mode), possibly zed too. thus it's doubly worth mastering

NOTE: *afaik, doom doesn't alter the original key-bindings (emacs not evil)*, instead relying on the leader-key maps here are the few exceptions i've found:

#+begin_src emacs-lisp
      ;; from  +emacs-bindings.eli
      ;; ...
      ;;; Global & plugin keybinds
      ;; ...
      "C-="  #'er/expand-region
    
      (:when (modulep! :ui popup)
        "C-x p"   #'+popup/other
        "C-`"     #'+popup/toggle
        "C-~"     #'+popup/raise)

        (:when (modulep! :ui neotree)
        "<f9>"    #'+neotree/open
        "<C-f9>"  #'+neotree/find-this-file

      ;;; treemacs
      (:when (modulep! :ui treemacs)
        "<f9>"   #'+treemacs/toggle
        "<C-f9>" #'treemacs-find-file))
#+end_src




describe-key

spc-/
  - meow-keypad-describe-key

spc-h-b
  - see all bindings interactively

*** some design notes on modifier keys, big keys, and other un-used special keys from my [helix config]


# notes from helix config to merge..
# some possible keys:
# **esc**
#  - should be free TODO: don't use OS to bind it
#  - could save for a list of shell commands/scripts
# `/~
# **arrow keys for four more modes!!**

NOTE: chromeos binds some modified keys by default:
  - a-down/up to page down/up
  - a-right/left to end/home
  - a-backspace to delete
    - you can re-bind them all to use search (caps lock) instead (which itself my be re-mapped/swapped with escape)
  - f11/f12 are disabled by default
    - and their alt mappings are difficult to rememeber anyway..
      - search-c/m-backspace

        

small un-bound keys:

back-quote (`)
  - ~ was used by games to toggle the dev console
  - used for lowercase/uppercase in helix
    - these key-chords were really annoying in emacs.. to the point of disabling them by default..!!
slash (/)
  - / was used by vim to signify search
    - maybe because file-paths have a lot of them..
back-slash (\)
  - can be big on certain keyboards..
  - in helix, runs a shell command (:sh ...)
    - TODO: see quickrun
    - though, less needed, as you'd likely just write (or generate with ai!) the functions with elisp..
  - i think | was used by helix for piping a program on a selection..??
    - it was a really interesting advanced function..
    - c-c a |
      - shell-command-on-region


other big keys:

escape
  - (swapped with caps-lock at os level)
  - <escape>/ESC
  - meow-escape
  - keyboard-escape-quit
    
caps-lock (search on chrome os)
  - swapped with escape at os level
    - NOTE: TODO: on chrome os, you need to re-bind search to something else, as it's an important modifier os key, like the super key on other oses. otherwise, you are short one key compared to keyboards with both caps-lock and super.
      - NOTE:on chrome os, maybe need to add a binding for task manager, which was search-escape: search-`
  - can re-map to alt instead, to avoid reaching the bottom-left corner key
    - this assumes left-control and left-alt are swapped
    - TODO: worth trying to provide an alternate for left-alt
      - would need another key for escape..
        - do i still need escape key? or is g enough..??
          - yeah, still need escape, g only works in normal-mode in the regular buffers, still need escape to quit pop-ups, completions, etc.
            - otherwise, you would have to bind g to escape on every little keypad/keymap binding pop-up

tab
  - NOTE: c/m-tab are often used by programs and window managers, possibly all major oses
  - cycle menus, words, completions, and certain major-mode stuff (org-cycle)
  - org uses it heavily
    - including s-tab
  - spc-x(/-spc) tab is really good too

backspace might be open to being re-mapped
  - maps to <DEL> by default
  - thanks to D (backward-delete), may not need
    - d, c-d, m-d all feel better than pressing backspace..
  - c-<DEL> and m-<DEL>
  - though, it's also nice to have a big ol' delete key too..
    - at least while transitioning..

return
  - TODO: overlaps with c-j??
  - org-mode makes a ton of use out of this one..
    - new line, new list item, new header, etc. (org-return)
  - i re-mapped this in helix for normal-mode only
    - this turned out to be quite a satisfying key to press when i did this in helix..
      - i used it as my own personal menu
        - it contained much of c-c q
          - (quit, save, restart, open/reload config, etc.)
        - sometimes i'd put bindings in it temporarily, until i figure out a place for them, or more likely, figure out i don't need them: i just have to learn more about the editor's functionalities




arrow-keys work as expected in emacs (thankfully!!):
  - moves one char
  - S- highlights
    - works in combination with other modifiers:
  - C-right/left moves by words
  - C-down/up moves by paragraphs
    - this one feels great!
  - M-down/up/right/left  drag-stuff-[arrow-key]
    - NOTE: careful with this one, it's easy to mess shit up(!!), thinking it's page-down/up..
    - c-x t transposes-lines

  

  
keys on bigger keyboards:
  - i stick to the laptop keys only
    
delete
  - <DEL>/DEL
    - backspace is mapped to this
page down/up
  - <next>, <prior>
insert





modifiers:

control and alt keys' (both sides) mappings are swapped on windows and chrome os at os level
  - NOTE: on an ancient chromebook, the left modifiers keys are huge, but the one in the corner is difficult to press. Whereas, the right modifier keys are smaller, and slightly more accessble to reach the right corner button, though still painful to reach the home-row j key..
  - TODO: *it's also possible to just alter one side, likely swap the left side to give access to left-control, and leave the right-side as is, with right-alt being accessible, giving a comfortable way to press both modifier keys..*
    - NOTE: not possible within default chromeos keyboard settings menu.. :/

(c)ontrol is the main modifier key to use

(m)eta/alt provides an alternative modifier key to use
  - NOTE: in helix and other terminal text editors, alt (no alt+shift) is reserved for terminal/tmux commands
    - thus no need for a weird modifier key combo.. these two are enough
  - these tend to be mapped to (alt)ernative functions
    - i haven't even explored these yet..

(c)ontrol + (m)eta
  - i haven't even explored these yet..
    - seems to be more code-oriented movement.. especially on C-M-? (don't know further down a key-sequence..)

(c)ontrol + (s)hift
  - was often used to denote the opposite action as control+key
    - this notion was by me, not emacs
      - this seems to have been replaced by meow-reverse (;)
        - ..genius!!
  - NOTE: this is usually un-bound in both terminal editors and emacs because terminals often prioritize the control modifier, making this input really unreliable
    - newer terminal emulators such as alacritty and kitty may have worked around this problem..
  - TODO: in emacs C-S-[key] maps to C-[key] as a fallback
    - maybe a meow thing..
  - this is generally open to re-map, but mostly limited to GUI-mode..

right-control and right-alt are rarely ever used because i tend to use the modifier keys on the left-side
  - TODO: really should fix this bad habit.. actually.. i have a lot of bad keyboard habits..

super (windows/mac key) is left untouched
  - linux kernal (and KDE Plasma) calls this meta, and alt remains alt
  - though it's possible over-ride it, providing yet another great key
    - better to over-ride the tab key instead
  - NOTE: chrome places it's super key in the caps-lock position

hyper is an extra option, though there isn't dedicated key for it..
  - this sounds like the perfect extra modifier key for tab/caps-lock/backspace

shift also symbolizes extending selection
  - S-[hjkl] all work as expected
  - S-[arrow-keys] work too

*** some ways to check bindings

spc-?
  - meow-cheat-sheet

spc-h-b-t

see [bindings-qwerty.el]

*** emacs

*run help-with-tutorial*
  - TODO: complete it!! it's very short

because emacs only had one editing mode, most of emacs original bindings (and bash before that..) rely on the modifier keys (as you need the rest to insert characters..)
  - see [[c-[key]]
  - see [[m-[key]] ??
  - (along with the global special keys)

    
some notes from the tutorial
it also had:
  - c-spc
    - mark two points to select
      - TODO: this is actually neat.. especially as you don't have so many keys to play with selecitons as you would in a modal editor..
        - it can even provide a better experience than using a mouse, when trying to select something across several screens of text..
      - TODO: re-bind it to something..
    - it also enters a sort interactive selection mode, so that you can expand/contract the selection
  - c-g as cancel
    - stops commands from executing
    - cancels last input in a key chord sequence
      - spc (in meow)
  - c-u
    - prefixes an argument to the next input
      - mostly numbers to repeat text-editing-related functions, but also flags (binary? just enter anything)
        - the repeat key concept (kakoune?) basically renders this deprecated, as it's a far more interactive experience
        - i also hated vim for using this..
  - c/m-v
    - page down/up
    - probably very satisfying on those old space keyboards..

  - m-e/a
    - moving by sentences is actually quite good, for both prose and code!
      - TODO: i don't see much need for c-a/e then.. should just combine their functionality..




   main movement:
   c-n/p = next/previous-line
     - j/k = meow-next/previous
   c-f/b = forward/backward-char
     - l/h = meow-left/right

   todo: these would be the first things i'd try to re-bind..
   c-j is similar to ret +electric
     - a little different from return's functionality..
     - todo: maybe can bind this to a movement function.. (next paragraph or page-down)
       - have c/m-v
     - todo: c-o vs c-j vs <ret> ??
     - open-line vs electic-newline-and-maybe-indent
   c-k kill-line
     - already have s for meow-kill instead
       - ahh, but need it for insert-mode..
     - m-k kill-sentence
       - kills up to .
       - an alt for f . s

     - sort of peek around, without moving the cursor..
     - i don't use this, but maybe i should..??
   c-h = help keymap
     - might be complicated to un-bind c-h, yet keep the menu.. :/

   c-spc
     - mark a point
   
   c-w = kill region
     - NOTE: notably not mneumonic..
     - fixme: doesn't work properly with meow selection..??
     - "{kill ("cut") text between point and mark."
       - intended to be use after making a selection using set-mark
     - warning: todo: really dangerous functionality when nothing is selected
       - not even sure what this does when a region isn't selected..
   m-w = kill-ring-save
     - s for save used by search
   
   c-i = tab (from <tab> key)
     - interesting.. indent, no need for a whole key, lol
       - it even feels more ergonomic!!
   <backtab> (s-<tab>) isn't bound (here in elisp-mode..)
     - but it is in org-mode..
   
   c-s = isearch-forward
     - i much prefer spc-s-s +default/search-buffer
     - but still very useful, just going to the next one..
       - doesn't feel very interactive..??
   c-r = isearch-backward
     - todo: now this is confusing!!
     - honestly should use shift modifier more..
       - ahhhh, but can't.. terminals..
  - m-r
    - move-to-window-line-top-bottom
      - TODO: this belongs with c-l 
  - m-s??
    - brings up some key-sequence..
  - c-m-s/r = regex search
     - now that's a good use of meta!
       - but why c-m-??
         - c-m- does have the theme of code-related stuff..
         - TODO: maybe can bind to both m- and c-m-..

*** meow-mode

TODO: move this heading to down to the end

aka normal-mode in moew-mode, which is confusing, insert-mode is the normal one in emacs.. and i still don't know what command-mode even is..!!

WARNING: the concept of modal editing adds a layer ("normal-mode", selection) on top of the default editing layer ("insert-mode"), thus adding a great mental burden (all letter keys, plus shift-modifier, and several symbol keys in vim; and still many in meow's minimal set of bindings). it also asdds two very oft used key-presses: entering and exiting that new layer.

NOTE: *you should FOCUS on the editing layer, as that's where all the work happens, and try to break the habit of re-entering the selection layer by default.*

the new layer is mostly a key-board oriented way of doing everything other than inserting characters, most of which is normally done by other input devices: movement, seeking, selecting and doing various things with that selection. Normally, you'd use a mouse or touch-screen for jumping, selection, and scrolling, in addition to the arrow keys and/or emacs movement bindings (c-npfb), including shift. With the new layer, you instead do everything with the key-board.

nowadays with prevalent touch-screens, i would imagine that is the way to go, especially for ergonomics, but also for reducing such a great mental burden. You don't think: just touch where you want the cursor to jump, or to select something, and with the ability to modify the touch input handler, the possibilities are endless: multiple-selection via multiple touches, gestures to swap selections, multi-tap to expand selection, and endless gestures to do anything else, with the power of 10+ inputs.  
  - *TODO: check/create touch input handler and bindings for emacs*


NOTE: these bindings by meow are amazing! i wouldn't change a thing!!

c-h b t
  - see them all, clearly!!
  - it's actually digestible..
    
see [meow docs TUTORIAL.org states keypad]



TODO: i wish there were some bindings for..:
  - comment
    - c-x c-;
      - but not c-x ;
    - via embark-act..
      - c-; / spc-a
      - actually, this is indeed where it should belong..
  - fold
    - c-c c-f -> fold key-map


compared to helix, notably lacks:
  - v for visual-mode
    - x, w (maybe more..) start it
  - g for goto-mode
    - *c-m- is certainly strange.. i might eventually just un-bind that entirely..*
  - m for match-mode
    - *replaces four keys?: [],.*
  - z for view-mode
    - though this is an existing emacs minor mode..
    - possibly broken by meow bindings..??
  - w window-mode
    - ??

**** un-bound
  - `
  - /
  - \

**** movement
  - hjkl
    - TODO: redundant, remove it..?
      - maybe used as a vim crutch..??
      - or maybe c-npfb is too painful..
      - this would free 4+4 crucial bindings..
    - HJKL for shift selection
      
  - the default emacs movement bindings are retained:
    - c-f/c-b and c-n/c-p == hjkl
    - m-f/m-b == e/b (but without selection)
    - m-n/m-p aren't bound by default
      - maps to c-n/p
      - i re-map them to the extremly useful forward/backward-paragraph
    - *c-a/c-e* > x,i/x,a
      - this one is really useful
        - c-a is interactive, jumping between first non-whitespace to beginning of line

**** special

  - ;
    - reverse cursor position on selection from kakoune
    - not only reverse cursor position, but reverses the direction of interactive selection!!
      
  - -
    - negative-argument allows you to do things in an opposite way too
      - (- f a) will select up to a in the reverse direction
        - though (f a ;) seems better seems more intuitive to me in this case.. can toggle the direction with ;

  - '
    - repeat
    - this is a blessing!! (it wasn't working in helix..)
    - f/t, '
      - find/till char, repeat
    - ]d, '
      - end of function, repeat

  - numbers (123456789) repeat a function n times
    - NOTE: this concept also appolies to leader key input
    - expand selection n times
    - find/till
  
**** insert
  - i/a & I/A
    - no need for o/O (open below/above) in vi

**** selection
  - g (; in evil)
    - cancel selection
    - TODO: repeat of escape..?
      - meow-cancel-selection vs meow-escape
      - as long as caps lock is escape, both are ergonomic to me..
  - z
    - undo selection
    - TODO: Z should be redo..? hmm..

  
  - most of these activate selection (meow-visual-line / visual-line-mode ??)
  - most of these expand current selection
    - arrow keys (with modifiers)
    - e/b, E/B
    - ]/[
    - ,/.


  - x
    - x i/a
    - x s
    - x ; x
  - m
    - merge
    - seems to select the space between the beginning of line and the end of the last line
      - press m again to select the space between two lines, regardless of where you cursor is
    - m s
      - merges the two lines
    - also places the cursor at the first-non-whitespace in the line, unlike x
      - m a
        - first non-whitespace
      - x i
        - beginning of line
      - m i ~= x a
        - end of line


  - w/e/b & W/E/B are much improved!

  - [ begin [thing]
  - ] end [thing]
  - , inner [thing]
  - . outer [thing]
    - replaces m (match) key-map of helix, which felt confusing 'n convoluted anyway.. having to press mim or mi. using letters is much better
    - use these for select to end/beginning of line(??): [,l and ],l; removes the need for creating key-bindings for this in helix. though quite important keys, it makes sense to put them here

**** seek (and select)
these will break the current selection (and create a new one), instead of expanding it

  - v visit
    - it's search filter is very picky: case-sensitive, symbols attaches to the beginning or end..
      - though maybe difficult to remember symbols, it makes it really good to narrow down choices
    - replaces / in vi
    - searches and selects
      - spc-s-s/S only searches
    - (then press n / ; n)
      - saves to regex-kill-ring
    - TODO: docs mention a way of setting regex for it..
    - TODO: haven't figured out how visit differs from isearch-   forward/backward (c-s, c-r)
      - actually, these seem like wayyy more complicated interactive functions.. full of even more emacs-styke key-bindings

  - o
    - meow-block
      - seeks out the next pair of closing-symbols, and goes to the end of it
        - great to seek function parameters
        - also great to seek the end of functions
          - perfect for editing comments
        - must be incredible for lisp..!!
        - inner/outer/begin/end thing doesn't seek: they assume you are in the thing

      - TODO: pressing it again doesn't hop to the next block
  - O
    - meow-to-block
      - can press again

  - f/t
    - find/till

**** delete shit
  - d/D
    - reverse delete!! (alt to backspace)
      - *TODO: try practicing this..?*
      - *TODO: this frees backspace!!*
  - s
    - pro-tip: pressing s when nothing is selected kills to end of line!!: genius!
      - no need for c-k
  - c
    - change
      - delete and insert
        - only saves one key press

**** search 'n replace
  - n
    - search last selection
      - expected to use ; for reverse search
  - r
    - replace
      - works as expected! (unlike helix..)
  - (see R, G, Y)

  - un-bound:
    - q, T, F, V, <, >, /, {, }, :, ", _, =, \, |
      - avoids mapping to non-nmeumonic(?) symbols

**** yank (copy) 'n paste, or replace, undo
  - TODO: i don't understand why this notion is reversed in meow..
    - meow-save 'n meow-yank
  - p
    - paste
  - (see P under advanced)
  - y
    - yank
  - r
    - replace
  - u
   - undo
     - kinda just tacked this one on here..

  - G
    - grab *secondary selection*
      - hooooooly shiiiit
  - R
    - *swap with grabbed/secondary selection*
  - Y
    - copy primary selection and paste over secondary selection
      - great in case you are in the area you want to paste in first, a sort of reverse copy/paste

**** advanced meow functions

  - U
    - *undo in selection*
    - TODO: maybe bind to vundo instead
  - P
    - *yank from kill ring* (meow-yank-pop)
      - stores killed and yanked text
      - seems to store system-clipboard yanked texts too!!
      - it's also interactive, so you can preview it in the buffer..!!

  - X and Q
    - meow-goto-line
    - TODO: can unbind these..


  - G
    - *secondary selection*
      - hooooooly shiiiit
    - meow-grab
  - R
    - *swap with selection*
    - meow-swap-grab
  - Y
    - copy primary selection and paste over secondary selection
      - great in case you are in the area you want to paste in first, a sort of reverse copy/paste
    - meow-sync-grab


  - *TODO: how to do multiple cursors??*
    - meow's keypad translate m input to meta
    - spc c spc m
      - found in doom bindings..
    - TODO: search for beacon-mode..
      
*** s-[key]

TODO: a lot of these are broken in insert-mode..

see meow-cheatsheet

see [[meow-mode]]
  - many are used by meow-mode's normal-mode

c-s-npfb

s-[arrow-keys]

s-hjkl (HJKL)

*** c-[key] and m-[key]

TODO: i haven't even got to these yet..!
  - TODO: emacs tutor
    - it's worth completing it this time..
    
these contain the original emacs bindings

these are generally consistent across modes (normal and insert) in meow

**** some basics:

key-chord trigger keys:
c-x
c-c
c-h


c-npfb
  - emacs basic movement keys

c-a/e
  - beginning-of-line/end-of-line
    - this combined with f simplifies cusor placement
- these two are immensely useful..
  - don't bother with meow's x i/a or m i/a!!
    
c-hjkl:
  - TODO: these suck
(c-h)
  - (help-map)
c-k
  - kill-line
c-j
  - return-and-maybe-indent
  - same as ret
    - TODO: seems redundant.. can try using it instead of return tho..
c-l
  - toggle center/peek bottom/top depending on cursor position
    - a very interesting key..

c-y
  - yank
    - NOTE: pastes: yanks from kill-ring, not yank from selection

c/m-v
  - next/previous page
  - NOTE: WTF at this key-binding..!
    - this must be a relic of the lisp keyboard..


  
c-ret
  - +default/new-line-below
    - does exactly what you want!
  - org has it's own function

c-[arrow-keys]
  - *basic nav*
    - *very useful*, usually beats ][ (end/beginning of shortcuts)

m-[arrow-keys]
 - drag stuff around

c-/
  - undo-fu-only-undo
  - use u for meow-undo instead
c-s-/
  - undo-redo
  - moved to U
- NOTE: these two are quite confusing in meow-mode..'
  
*** c-s-[key]

adds selection to a few movement keys binding sets
  - c-npfb
  - c-arrow keys
  - c-hjkl -> s-hjkl
    - *NOTE: these aren't movement keys*
      - these are keys exclusive to modal bindings
      - *this is notably confusing..*
        - it may be better to get used to c-npfb..
    
generally un-bound, often mapped to c-[key]
  - this is due to legacy terminal app input handlers
  - contemporary terminal apps like wezterm, alacritty, and kitty handle this input correctly
  - *this makes it a good candidate set of modified key bindings to personally abuse..*

    
doom binds:

  - tl;dr
     - *NOTE: if you bind c-s-r, re-bind vertico-repeat*
       
  - c-s-s/r
    - used by completion plugins:
    - s for swiper (ivy/helm)
    - r for resume (ivy/helm) or repeat (vertico)
      - NOTE: doom uses vertico by default
    - though not bad, as it is a kind of search..
    - TODO: maybe need to add alt bindings to this..

*** [f-keys]

NOTE: with a chromebook, i re-bind the search key (below tab) to escape, which blocks the default search+function key binding
  - must use escape + [f-key]

on my chromebook
  - f1/f2 have left/right arrows etched on them, some kind of special back/forward key
    - <XF86backward>, <XF86forward>
    - these are auto-magically bound to next/prev buffer!!
      - can be used to bind to next/prev window, workspace/tab, etc.


i think doom uses these to toggle various modules, such as treemacs (file/code explorer pane), minimap?, etc.
  - see [doom bindings file]
  
  
can keep these empty for project specific bindings, like calling scripts, ci/cd, etc. project actions

  
quite minimal..

TODO: merge this bit:
function keys
TODO: i haven't even tried the function keys yet..!
  - could use for toggling plugins (tree panel, terminal, build/run/de-bug, etc.).. but would i use it that often..?
  - could use for display management (buffer/window/tab) too
    - f1/f2 seems to be bound to previous/next buffer..
      - TODO: change system keys to require using a modifier key?

**** only these two are useful:
f1
  - help
f12
  - *gui menu*
    - also can get here by clicking on various items on the status-line
      - major mode menu, minor mode menu
      - version control menu
      - line and column menu

**** doom's toggles
f9
  - neotree / treemacs?

**** the rest can be unbound:
f2
  - 2C 2 column functions
  - c-x 6
    - TODO: i dunno about this one.. loll
      - maybe ask the emacs folks..
f3
  - define keyboard macro
    - makes sense to be away from the normal keys..
  - NOTE: possibly redundant, can remove
    - c-x (
    - c-x )
      - strange place..
f4
  - execute keyboard macro
    - c-x k k
      - again in normal mode
    - a little too deep..

*** mini-buffer

*TODO: how to scroll through the c-x list..?*
  - only page down/up??
    - i might have to re-bind down/up arrows..

just press escape to close mini-buffers including pop-ups
  - no need to buffer-kill them

*PRO-TIP: c-s to show search history*
*PRO-TIP: m-s to use regex search*

press the initial key-chord, then, in the popup mini-buffer, press c-h to fuzzy search it
  - TODO: what?? maybe in doom..??
    
** modules
*** org-mode

TODO: should try the tutorial.. if there is one..

**** how it works

c-h m
  - describe-mode

headings as main structure unit
  - ways to navigate them: org-shifttab, org-goto, TODO: probably more..

headings can be tagged
  - *TODO: this is a little strange to me.. i think i prefer line-based tags..*
  - *TODO: remove most tags and add personal tags here: NOTE, etc.*
  - headings are categorized by: inactive and active

**** bindings

interesting auto-indent..

i like * over # for headings.. though it could've been any symbol for easy parsing..
  - * is placed in an odd spot on the keyboard though..
    - probably expected to use c/m-return anyway.. along with m-left/right
  - # is used for comments in many prog langs anyway, they pre-date markdown by far..

***** a few very important bindings
  
tab
  - fold/unfold headings, sub-headings, sub-sub-headings..
    - my favorite feature.. missing from helix??

shift-tab
  - toggle: overview, with sub-headings, all content
  - *great for navigation / quickly grasping*
    - though, a little overview panel would be better..
  - org-shifttab

org-goto
  - spc-c-j
  - *great way to navigate, interactively*.. code files def need this mode!!

***** the rest
  
*c-c l*
  - go through this first..

c-c l h
  - org-toggle-heading
  
org-insert-link
  - spc l l l
  - *file links actually open the file or directory (via dired)!!*
    -  this is quite incredible... just have to make sure the files are under the same repo..

s-[arrow-keys]
  - TODO: seems to over-ride c-s- shortcuts.. hmmm
  - NOTE: org-mode overrides these to provide more bindings, based on where your cursor is:
    - (org-support-shift-select) to use original bindings
  - TODO: NOTE: "to use shift-selection customize org-support-shift-select"
  - on heading
    - cycle tag (TODO, [X]..)
    - cycle another set of tags..? ([#A], [#B]..)
  - on list
    - cycle indent symbol
    - begin/end of list

(c-[arrow-keys] aren't bound)

m-right/left
  - on heading
    - promote/demote heading
  - on list
    - un/indent list right/left (normal-mode)

c-ret
  - if on a list
    - insert list-item
  - if on empty space
    - insert heading

m-ret
  - same as c-ret?

c-m-ret
  - insert new heading (highest-level), no matter what?

**** org-babel

this is awesome for dynamics langs, as it allows you to mix human language writing with source code blocks, which you could execute at run-time
  - i'm guessing jupyter notebooks derive from this concept.. where research writing that involves programming (as proof?) can have writing mix with code in the same document

otherwise, it's similar to markdown's tags for code-blocks, which indicates to the editor/display program that this is code, and if the program has functionality, it may display it with some syntax highlighting

c-c c-v / spc c v
  - demarcate block
    - TODO: change to c? (check-source-block checks header arguments..??)
      - maybe flip with '!'?

*** magit
github desktop, or likely any other gui, seems to be much simpler to grasp and use.. However, upon my first comparison, *it seems magit show far more details in the diff changes, whereas github desktop glances over it*, just highlighting the whole line red or green. So, it may be worth playing with some more..

spc-v
  - version control
  - enable magit and vc-gutter modules to show git functions

spc-v-g
  - status
  - start here

P push
  - p push (default)
    - main/origin?
  - u upstream?
    - main/origin?
*** dired
mark files 'n folders, then take action
  - and remember, can use favorite emacs commands to search text in the buffer!

m(ark)
u(undo)

capital keys for actions, for safety reasons
  - R, D
    - R is mv, use it for rename, move, cut/paste

*** flycheck (syntax checker)
just use the gui, mode-line, click on the little error/warning/info icons on the botttom right

c-c ! to trigger the menu
  - this is a strange binding..
    - i guess it does belong under code though.. :/
      - yet so does spc-k..
        - TODO: yeah, spc-k is a good place for it..

*** vundo

TODO: mark, diff??
  - *hooollyyy shiiiiit*
*** dynamic langs

i'm guessing these functions work with several languages with dynamic runtimes
  - lisp
    - all
  - *including ruby!!*
    - yup, via robe plugin
  - *TODO: elixir??*
    - it'll be sick to jump from ruby to elixir dev, in emacs!!
  - python??
  - lua?



**** introspection related

explore dynamic programs (including emacs) interactively via emacs

c-c c / spc-l
  - language-dependent key-map
  - *bindings for language-related plugins will pop up here*
    
c-c c g / spc-l g (meow)
  - *interactively search through all libs, functions, vars*
  - goto key-map
  - find-function
  - find-var
  - note: if it's a buffer of emacs code, it will search through emacs, similar to the helpful- functions

  
  
**** eval related 
spc-e
  - *note: if it's emacs-lisp, you can simply feed code into emacs*, no need for a seperate repl process!
  
spc-o-r
  - +eval/open-repl-other-window
    - *note: don't bother with editing within the repl window, terminal windows have funky input..*
  - only need this to start it, then can try to do as much as you can within emacs buffers

run (eval) regions of code
  - spc-k-e / spc-e (doom-meow)
    - +eval/buffer-or-region
  - i think this merely runs the code (TODO: by insantiating a sub-process?), outputting anything to the echo areas..
    - except: in the case of emacs-lisp, in which i think it behaves like +eval/send-region-to-repl

TODO: run the entire program in repl?
  - what happens when you run the main/entrance function of a program?
  - then can run any function..??
  
send regions of code to a repl
  - (after to open a repl/vm? process)
  - then can run functions, macros, etc., or use data created (vars, objects, etc.)
  - spc-k-s
    - +eval/send-region-to-repl
  - spc-c-??


**** lisp

eventually, you'll probably naturally read enough lisp code when using emacs
  - spc-f-e
    - find file in ~/.emacs.d

c-( / c-s-9
  - auto-add parens in the right place
  - if you have paraedit?
m-( / c-s-0
  - move to next expression(?) and auto-indent

  
** meow's inherent god-like-mode

NOTE: it's wayyyy more comfortable to press space-bar over any of the bottom-left key-chords (c-x, c-c). Even (spc x spc) is better, though it adds two more key-presses. The right alt key is the size of a normal key, and still hard to reach with my thumb, making (m-x) particularly difficult.. :/. I tried using emacs' original key-chords while playing with vanilla, but it felt like i was using a space cadet keyboard.. my hands never on the home row..
  - TODO: try to get into habit of pressing right-control with thumb
  - try finding some way to swap the right modifier keys on a chromebook..? nah.. then i'd have to rely on using left control for c-x and c-c!!


adds an alternate spc key-chord for modifier key combos
  - NOTE: some of these are hidden from the meow menu..
see [meow docs TUTORIAL.org under keypad]


TODO: get my answer from https://www.reddit.com/r/emacs/comments/1oacbht/halp_im_drowning_by_keybindings_doommeow_includes/

adds space as an alternate key to trigger key-chords, as opposed to modifier key combos

*NOTE: all of these are hidden from the meow spc menu..*, hence it being quite small.. i guess it assumes you remember these..??



from meow's readme.org
 - when a key other than =x= / =h= / =c= / =m= / =g= is pressed in Keypad state, it is directly looked up in the leader keymap. This module sets =doom-leader-map= (bound to =C-c= by default) as the leader keymap. So, for example, =SPC s p= produces =C-c s p=.


TODO: merge with above
  - This is done cleverly, too. The first key you press after SPC becomes the modifier that is applied to every key following it. So C-x C-f becomes <SPC> x f, and C-c C-v C-t still becomes <SPC> c v t. To escape modification, you press SPC again. Critically, you can omit the SPC if the key you press matches exactly one non-modified key and no modified-keys.


see [[file:/home/ra/.doom.d/modules/editor/meow/config.el][meow config]]
  - link to where doom binds to meow..??

  - numbers (123456789) are used as arguments for functions
    - this is some advanced shit..
    
  - spc-spc
    - binds to c-space..??
      - set mark

  - spc-x-[key] (c-x, c-[key])
    - NOTE: the second letter is automatically adds c- modifier
      - TODO: how to use use a normal letter..??

  - spc-c-[key] (c-c, c-[key])

  - spc-m-[key] (m-[key])
    - a good way to see otherwise hidden bindings

  - spc-g (c-m-[key])
    - go
      - more navigation stuff..??
        - TODO: looks pretty useless.. might be able to easily trim this off..
          - basic navigation via hjkl, arrow-keys + modifiers, ][, seem to cover most of it..
      - matches c-m-[arrow keys]

  - spc-x-spc, spc-c-spc
    - *doom's bindings*
      - *very useful to intuitively find more useful functions from doom's config..*
        - TODO: merge c-x functions and spc (doom)
          - sould be pretty easy..
        - TODO: marge c-c function over time (major-mode-dependent)
          - this shit never ends..!
** some other binding packages
*** god-mode

i think started the whole space key as alt to modifiers..??

*** boon

https://github.com/jyp/boon
  - also contains good comparison notes on all other pop key-bindings packages

boon notably simply *binds x to c-x and c to c-c, for the first key in the key sequence*
  - thus it simply ends the whole modifier key dilemma..?
    - nope.. you'd still need to press c-? for the next key sequence.. but for the most part, it's great!
  - 
        
** key-chords


#+begin_src emacs-lisp

;; from the top of +emacs-bindings.el

;; Sensible default key bindings for non-evil users
(setq doom-leader-alt-key "C-c"
      doom-localleader-alt-key "C-c l")
;;...
(map! :leader
      (:prefix ("l" . "<localleader>")) ; bound locally
  ;; - NOTE: looks like a virtual key input..
      
#+end_src

      
c-c (emacs)
  - TODO: worth looking at how it used to be in vanilla emacs

c-c / spc (doom)
  - see [[file:/home/ra/.emacs.d/modules/config/default/+emacs-bindings.el][emacs-bindings.el]]
    - doom's "sensible default key bindings for non-evil users"
    - doom-meow uses this, only altering it slightly:
    - spc-m
        - multiple cursors
    - adds localleader concept (spc-l)
    - TODO: grab bindings from here (from both emacs and evil bindings)
      - neotree?
        - TODO: try enable module?
        - f9
      - remote menu?
        - spc-r
        - TODO: try enable 'upload' module
      - TODO: try using one of the e-mail modules!
    - TODO: alter mini-buffer auto-completion bindings
      - find
        - ;;; completion (in-buffer)
        - (:when (modulep! :completion company)

c-c / spc (meow-doom)
  - meow-doom re-uses doom's leader-key bindings (see above)
    - there are a few changes:
      - m for meta, not multiple cursors
      - (TODO: i think g worked the same way in doom too..??)
      - spc-c (code) -> c-k
        - to keep original c-c chord
  - moew "keypad"
    - this is a special interactive program, not just a mere chord
  - modifier key inputs are translated:
    - *NOTE: by default, it uses c- modifier, and if no command exists there, it falls-back to no-modifier
    - m -> m-
    - g -> c-m-
    - spc -> (no-modifers, "literal")
  - *NOTE: m-spc in insert mode triggers m-x*

c-x / spc-x-spc
  - emacs's original emacs key-chord
    - neither meow nor doom alters this
    - in doom's evil bindings, many of these are spread across the leader-key bindings, thus breaking away from this traditional binding
  - *TODO: NOTE: still has a few very important functions:*
    - *TODO: i haven't quite decided what to do about this.. keep it, alter it, make a new one..??*
    - buffers
      - kill buffer
      - next/prev buffer
    - windows key-map
      - in addition to these frequently-used bindings on the c-x key-map:
      - 123
      - other-window
        - TODO: also m-o? i must've re-bound this to expand region.. hmm
    - projects
    - save
    - directory
      - note: can also arrive here via find file by selecting a directory
    - dired-(j)ump
    - tab indent interactively!!
    - left/right arrows
      - left/right buffer
    - c-x D
      - delete this file! never have to leave emacs! :D
      - TODO: move to spc f by doom..?? i don't think so..

  
    - NOTE: doom updates the following:
      
#+begin_src emacs-lisp
      ;; from +emacs-bindings.el

      ;;; buffer management
      "C-x b"       #'switch-to-buffer
      "C-x 4 b"     #'switch-to-buffer-other-window
      (:when (modulep! :ui workspaces)
        "C-x b"       #'persp-switch-to-buffer
        "C-x B"       #'switch-to-buffer
        "C-x 4 B"     #'switch-to-buffer-other-window
        (:when (modulep! :completion ivy)
          "C-x 4 b"   #'+ivy/switch-workspace-buffer-other-window))
      "C-x C-b"     #'ibuffer
      "C-x K"       #'doom/kill-this-buffer-in-all-windows

      ;;; popups
      (:when (modulep! :ui popup)
        "C-x p"   #'+popup/other
#+end_src



c-x c-? / spc-x
   - looks really strange.. full of functions i wouldn't use..
   - i think just alts to c-x

c-c c-?, spc-c (doom/meow)
  - *major-mode bindings*
  - *this is a great way to quickly and intuitively learn the main functions/bindings of a major mode*

c-c l / spc-l (doom-meow) / spc-m (doom+evil?)
  - +localleader
  - *TODO: another optional set of major-mode bindings?*
    - for example, in org-mode and elisp-mode

c-c k / spc-l (doom+evil?) / spc-k (doom-meow)
  - maybe was originally l or some other letter, but moved to k in meow??
  - lsp stuff

** doom-meow's leader-keys
  - NOTE: uses a slightly different set of bindings in meow-doom
    - but looks like the default bindings...??:
      - (default +bindings +smartparens)) ; NOTE: needed for meow
      - at the end of init file
    - NOTE: doom's space key-chords are far more intutive (especially if coming from vi), whereas meow's are sparse, perhaps closer to vanilla, in need of customization..?




TODO: import leader key bindings from helix
TODO: merge doom (emacs) base leader key bindings
TODO: merge doom +evil leader key bindings
  - see [[file:/home/ra/.emacs.d/modules/config/default/][doom bindings]], evil-bindings.el seems to have everything... hmmmm, can that be stuffed under spc-d?

initially can keep them seperate, in seperate keys (spc-[key]), likely under spc-d, spc-j, and keep spc-j as my own custom menu


see /home/ra/.doom.d/modules/editor/meow/autoload/bindings-qwerty.el
  - TODO: not sure how to paste a link in the mini-buffer..
  - this has a list of functions
    - TODO: use org-babel to display the reference code in this file?

c-h b k
  - search and see various keymaps
  - doom's start with doom-leader-
  - ctl-x-keymap

c-h b m
  - *which-key-show-major-mode*




  
spc (meow)
- moew bindings
  - TODO: find a way to add name to the leader category
    - instead of 'v' show '(v)ersion'
  - mneumonic
  - &
    - aya/yas
  - tab
    - pro-tip: if a region is highlighted, auto-indents
    - alt: spc-a-tab
  - a(ction) embark-act
    - *interactive way of using the selected region to do something*
    - by default, if nothing is selected, it'll select the current line
    - search
    - format
      - | shell-command-on-region
      - macro
        - keyboard macro, not lisp macro..
      - align
      - delete duplicated lines
      - indent
      - lots more..

      - next item (org-next-item)
      - previous item
        - *an interactive way for navigating an org file*
          - whoa.. this shit never ends..! :D
            - i love it, lol. *emacs is an endless game for interacting with text*
  - buffers (doom+evil)
    - i mean, maybe there aren't enough bindings related to buffers for it to warrant it's own key-map..
  - eval
    - TODO: don't think this deserves an entire key..
      - maybe more useful for lisp..??
  - file
    - f, F (spc-spc in evil/helix), r, d, p
      - pro-tip: spc-f-f creates a file if it doesn't exist!
    - m(ove)
      - much better than jumping to terminal..
  - go
    - an alt for c-m-[key] bindings
      - *TODO: i need a key-map for c- and m- too*.. for more intuitive learning..
        - otherwise have to search through the keymaps :/
    - semantic-based movement (instead of words m-, chars (no-modifier), symbols)
  - insert
    - unicode, emoji, file-name/path
    - TODO: never use..
  - j
    - NOTE: well-placed key left un-bound for the user to create their own menu..?
  - k(ode)?
    - k
      - doc
    - d(ef)
    - *lsp*
      - i think it was chosen due to it's location: the most used key
  - l(anguage)? (c-c, l)
    - *major-mode bindings*
  - notes
    - org-mode notes
      - TODO: set-up org notes folder
        - *HOLY SHIT, really need this..!*
  - open
    - shell, debugger, TODO: seems like a good place to open other programs..
  - project
  - quit
    - quickload, quicksave, etc.
  - search
    - search (buffer) (/ in evil), project (spc-/ in evil), cw(d)
    - otherwise, can use spc-a-(c+)s/r
  - universal
    - TODO: meow-universal-argument
  - toggle
    - zen/Zen full-screen, word-wrap, line-numbers
  - workspace
    - w
      - select
        - handles/no need for the following key-bindings:
        - c, n, p, 1..9
      - create, next, prev
    - l
      - load
        - NOTE: can find several autosaves here, just in case..!
        - alt: spc q L (doom/load-session)
  - window? (doom+evil)
  - version control
    - g (= magit command)


  - / meow-keypad-describe-key
    - maybe useful if you don't have enough screen-space to see the commands in the mini-buffer..?
    - c-h k for describe-key-briefly
      - TODO: might want this instead..
  - ? cheat-sheet

    
  - </> (doom+evil?)
    - switch buffer
    - strange binding.. but makes sense
      - i don't like holding shift on a second key.. but it is closer than the arrow keys..
      - NOTE: i think needed for when terminals mis-input arrow keys

  
  - spc-spc
    - bound to c-spc..??
    - set-mark-command
  

  





  
** TODO merge some other useful key chord and leader-key bindings

TODO: merge with above..


the last notes from emacs-key-mappings.txt:
  - kinda incomprensible..
  - abbrev
    - autocomplete
  - abbrev-with-popup-window

m
  - / (or c-p in vi's insert-mode)
    - autocomplete

      


m-spc
      (:when (modulep! :editor objed +manual)
        "M-SPC"     #'objed-activate)


m-x / spc-m-x (meow) / : (evil) / m-/ (evil?)
  - command prompt
  - contains every function available (~7500 with default doom install, ~6750 with meow instead of evil key-bindings)
    - note: this is a subset of all functions: (c-h f) shows ~35k
  - usually [module]-[function]
  - this one notably is neither a key-chord nor on the key-map..
    - i added to m-spc

    
c-x/spc-x (spc-b in doom?)
  - *TODO: create another binding for this..?? or keep the original emacs way?*
    - *create my own menu via spc-[my-key]*
      - *start with nothing, building up from scratch*
    - *spc-j is a good start*
    - *or could put under spc-f, to make it files 'n buffers*
      - spc-f-b/B are unbound!
     
  - buffers
    - NOTE: this menu is missing in meow
    - ordered by use:
  - s
    - save
    - bad habit..
  - b/B/spc-b-i
  - *buffer list in dired* and *search buffer interactively*
    - exactly what i wanted when using helix!!
  - switch-to-buffer vs persp-switch-to-buffer
    - found in doom bindings
    - it seems persp gets rid of the recent files list and all of emacs temporary files
      - TODO: update binding
  - k/K
    - kill
  - left/right
    - next/previous buffer
      - TODO: yay!! can finally use, now that gui emacs works!!
        - try this out some more..

      
c-x </>
  - scroll left/right??
    - disabled, lol, rip
  
spc-x-;
  - comment-line
  - spc-c-; depending on the mode..




* pre-configs

https://github.com/emacs-tw/awesome-emacs#starter-kit


*doom-meow*
  - what i'm currently learning/discovering emacs on..

*DOOM*
  - PERSONAL NOTE: i had a great initial experience using this, felt wayyyy easier and wayyyy more intuitive and wayyyy smarter (built-in functions do what you except) than using neovim!
    - helix seems to have taken much of it's space-key-chord shortcuts from doom, making it an easy jump
  - "Doom is a configuration framework for [[https://www.gnu.org/software/emacs/][GNU Emacs 26.3+]] tailored for Emacs bankruptcy veterans who want less framework in their frameworks and the performance of a hand rolled config (or better). It can be a foundation for your own config or a resource for Emacs enthusiasts to learn more about our favorite OS.

    Doom is an opinionated collection of reasonable (and optional) defaults with a focus on performance (both runtime and startup) and on abstraction-light, readable code design, so that there is less between you and Emacs.""
  - "fast, closer to metal, opinionated, no forced plug-ins, nix/guix"
  - 150 modules! ..and that's just what's on by default!
  - "If you want something closer to what you know, and less involved to customize (less barebones basically), doom is what you want."
  - "I have tried them both and vanilla as well. I like doom the best - it has better shortcuts out the box, less buggy, uses traditional elisp for configuration as opposed to spacemacs which uses a proprietary thing you have to learn."
  - recommended by that one emacs guy from noisebridge
  - the maintainer treats it like a full-time job
    - it might just be..

x/spacemacs
  - "a community-drive emacs distro"
    - sounds like 'oh my zsh', which is *not good*

prelude
  - TODO: worth trying, now that you can try emacs with different configs via a flag
    - i much prefer going backwards: having all the tools ready, slowly discovering thing over time. Thus doom is the way to go for me. And so far, i see little reason to try anything else.. i can always un-bind crap.
      - also, there's just no way to beat the maintainer of doom, he puts an incredible amount of work into it that is a full-time job, a job that i don't want to do
  - way more stripped down, much closer to vanilla emacs
  - Prelude is basically a very light starter kit, whereas doom is a whole garage full of tools. (This does not mean doom has more utility, it just comes with more going on out of the box)
  - recommended by that one emacs guy from noisebridge





* doom
** install (doom)
follow the directions on the github
fish_add_path ~/.config/emacs/bin

windows:
scoop install emacs

set $env:home = "$home" in powershell profile
append $home/.emacs.d/bin to path

make folder in $home/.emacs.d
copy a clone of the doom repo there

doom sync
  - doom sync --aot
    - compiles natively
      - TODO: test if worth or not... maybe not worth it if updating frequently..
doom doctor
  - check for problems
doom run

NOTE: at the moment, must use bash to run it:
."C:\program files\Git\bin\sh.exe
  - run git bash
    - i think exists under msys2 (installed via scoop) too
doom run

add a shortcut
  - "C:\program files\git\bin\sh.exe" -c "/c/Users/ra/.emacs.d/bin/doom run"

..YAY! :D



https://gist.github.com/rahil627/e9d150adc8dcc36846f5f6d0a4465665
  - my gist on installing doom for chromeos, including building emacs 29

** notes on how to maintain doom (+ post-install notes)



my notes:
see more notes in config



from github repo page:
doom sync
  - to synchronize your private config with Doom by installing missing packages, removing orphaned packages, and regenerating caches. Run this whenever you modify your private init.el or packages.el, or install/remove an Emacs package through your OS package manager (e.g. mu4e or agda).
doom upgrade
  - to update Doom to the latest release & all installed packages.
doom doctor
  - to diagnose common issues with your system and config.
doom env
  - to dump a snapshot of your shell environment to a file that Doom will load at startup. This allows Emacs to inherit your PATH, among other things.
doom build to recompile all installed packages (use this if you up/downgrade Emacs).


post-install notes: (from the doom install cli script)
But before you doom yourself, here are some things you should know:

1. Don't forget to run 'doom sync', then restart Emacs, after modifying
   ~/.doom.d/init.el or ~/.doom.d/packages.el.

   This command ensures needed packages are installed, orphaned packages are
   removed, and your autoloads/cache files are up to date. When in doubt, run
   'doom sync'!

2. If something goes wrong, run `doom doctor`. It diagnoses common issues with
   your environment and setup, and may offer clues about what is wrong.

3. Use 'doom upgrade' to update Doom. Doing it any other way will require
   additional steps. Run 'doom help upgrade' to understand those extra steps.

4. Access Doom's documentation from within Emacs via 'SPC h d h' or 'C-h d h'
   (or 'M-x doom/help')

Have fun!

*** when shit breaks

it's time to learn vanilla emacs

emacs -q
  - pure emacs, --no-init-file
  - it's actually quite okay.. it reminds me of notepad++, with a beige background color and colorful org headers..
    - i'm surprised org-mode works.. with colorful headings!!

emacs -Q
  - or --quick
    - even leaner..


** install icons
run nerd-icons-install-fonts function within emacs
  - TODO: not working..

** install meow key-bindings for doom
doom-meow
https://github.com/meow-edit/doom-meow
mkdir -p ~/.doom.d/modules/editor && git clone https://github.com/meow-edit/doom-meow ~/.doom.d/modules/editor/meow

Enable this module in your doom! block. (add (meow +your-desired-flags...) after the :editor section in init.el)

After you doom sync and restart Emacs, Meow will start in Normal state, so make sure that bindings have been set up; see Module flags.

The leader and localleader bindings are defined in <a href=doom-module::config default +bindings>doom-module::config default +bindings, so that module is required for them to work.

This module will not work smoothly with doom-module::editor evil, doom-module::editor god, or doom-module::editor objed. You must disable those modules in your doom! block to use this one.

