

* WTF: WARNING: BEWARE OF SUDO APT REMOVE

less /var/log/apt/history.log
  - check the damage


 these were the notable packages removed:
  - *ruby-dev*
    - TODO: what's the difference between dev and a standard install?

  meh, ruby is all i need, i can let it re-install the rest when needed:      
  - jre-headless, opendjdk-17-jre-headless
  - python-pip
    - lol, i can survive without this..
  - perl just won't die..
  - java-common





* some random notes

to install an app manually:
copy the binary to /usr/bin/ for most distros
then you should be able to run the binary via command line
  - scoop handles this crap for you
  

* original file


CONCLUSION: forget linux, stick to windows for personal computers, and just get by with emacs on linux servers
  - also, *scoop is the best package manager i've used! portable apps all the way, and it handles setting up symlinks, start-up env vars, etc. for you!!*


  

* why linux (sucks)

https://www.reddit.com/r/pop_os/comments/xuq2pm/can_someone_explain_to_me_like_im_five_why_linux/
macOS and Windows has a single platform vendor, Apple and Microsoft.

Apple has a complete vertical stack integration; they control both the hardware and software, so they can provide a tight experience for their consumers.

In addition, Apple continuously update their APIs and guidelines for app design, rules, and issue platform-wide updates once a year with their annual software refreshes. This allows developers with predicable schedules and docs to update their apps. This also allows Apple to simplify the packaging experience, such as the DMG and PKG.

Microsoft has both EXE, MSI but they're not as tight as Apple because of backward compat support, which means apps often have to deal with registry, hardware tech (32bit/64bit/arm) that macOS devs do not have to deal with. This is because Microsoft does not own the hardware stack, so they have to provide backward compat to ensure everyone can use any software compiled to Windows for the past few decades, not permitting an easy one-win solution like Apple.

Linux is an open source community project, it belongs to the public with no restrictions. There's no single vendor (Linus is Benevolent dictator for life but he doesn't really fully control it). There are several standard bodies to try to centralize the work going into Linux like free desktop APIs, but no one is required to follow it. Since there's no enforcement at all levels, there's also no way to ensure a consistent packaging experience for all users either. We do have some universal packaging solution such as Flatpak, AppImage, Snap but they're not available in all distros, it is up to the public.

However, note majority of users download their apps from the package manager; apt, dnf, etc or the software store apps that is available for their distro. So they don't have to deal with the packaging either.





* distros (distributions)

conclusion:

0. TODO: research 'n try debian unstable
   - TODO: does WSL use debian by default?
   - chromeos uses debian for it's linux container by default

1. openSUSE leap for slower releases

e. openSUSE tumbleweed vs archlinux for latest releases
   - i def don't need these, as i'll be using windows for my personal computer..
    
def not NixOS
  - if i really wanted to torture myself and try it, just start with the user-created package manager: home manager (nixOS just goes further by using nix, the declarative langauge, to set the OS)




** list (of distros)

https://www.reddit.com/r/openSUSE/comments/x7ge7j/thinking_about_moving_from_arch_based_to_opensuse/

https://www.reddit.com/r/NixOS/comments/zwqaxz/arch_user_convince_me_to_hop_to_nix/


*** arch linux
  - newer, community-made (and not the more slower, older, enterprise-feeling FOSS community behind debian)
  - "for people that want to install linux from nothing (or the most minimal amount of software)"
    - though, there is an install script (archinstall) to help/guide newer users
    - "Arch is very barebones once installed, you end up with a functioning terminal and only essential packages installed. For example, you won't even have sudo unless you install it. So if you want an ultra refined, customised setup where you're responsible for installing and configuring everything on your system, Arch. If you want to install your system with a DE and get to using it right away, Endeavour."
    - have distros to ease this:
      - **endevourOS**
        - just adds installers, install scripts, etc. *making life easier for installs, especially drivers*
      - manjaro
        - less arch, some weird mish-mash of beginner-friendliness and arch
  - rolling release system-packages + user-maintained user-packages, *continuously / no release*
    - meaning, you must update the entire system every time you want to get package that uses another package (dependency) that has a release newer than your system
      - aka **you must update your entire system nearly every-time you want to get a package!!**
    - tested by a volunteer testing team
  - *great wiki: documentation on everything, great way to learn linux*
  - *"Arch recommends you check the wiki before every update to see if the update is going to break something. Tumbleweed just works"*
  - *in general, to install or config apps, you read the wiki and manually config it yourself*
  - **if it crashes, you're screwed, so you def need to setup a backup system and backup frequently**
    - *need to install your own backup software (BtrFs, etc.)*

*** openSUSE
  - an old staple made by an enterprise server company
  - *for people that just want a hassle-free working system that doesn't want to waste time tinkering and building everything from scratch*
      - yep, that's me..!
  - *provides options to customize making a great out-of-the-box experience*
    - YaST, an all-in-one system config tool
    - "*snapper saves your @$$*"
    - AUR (arch's user repo) > OBS
    - BtrFs
      - a file-system that allows *quick 'n small snapshots*, among many other contemporary disk-related features
    
  - Tumbleweed
    - *rolling release, 1 snapshot max per day, so more like release nearly every-day*
      - tested by a company
    - "*Tumbleweed feels like Fedora, works like arch and installs like Debian. The best of all.*"

  - Leap
    - intervalled release
      - TODO: or is the other way around..?? i mean tumbleweed rolls, but it's slow, not leaping..

*** fedora
  - by red hat enterprise
    - (though not sure if RHEL exists anymore..)
  - competed with debian for a long long time as most popular distro
  - *releases every 6 months*
  - *dnf > apt*
    - dnf history list
    - dnf history undo
  - *encourages using flatpaks (cross-platform, portable packages) over third-party repos*

*** debian
  - *releases every 2 years!!*
    - meaning *your software will nearly always be out-dated!*
    - the debian security team only works on the current release, so you must update it (except for LTS versions, which have security updates for 5 years)
  - *can use unstable and testing/"sid" branches of the repo for latest, untested software*
    - TODO: wouldn't this be better than arch/leap?
  - the free and open-source (FOSS) standard distro
  - the main community-based distro
    - (as opposed to company-owned ubuntu, red hat, etc.)
  - to use more recent packages, can download them using snap, flatpak, etc.
    - benefits from being safe/sandboxed too

*** special
**** NixOS
  - **reproducible env via declarative configs**
  - https://www.felixsanz.dev/articles/nixos-made-me-go-back-to-windows
    - a soid personal blog post of a person who went from using linux as a child, mostly arch linux, for 20 years, then trying nixOS, then running to Windows
    - "Without a doubt this is the feature of NixOS that I liked the most. Nix is, besides a package manager, a pure, functional, lazy, declarative and reproducible programming language to express (in .nix files) the state of your system. In other words, you will not have to execute commands that you will later forget nor will you have to modify files scattered around the system. You will perform all the configuration of your system through files that you can save in Git or wherever you want."
  - In these files you can specify the packages that must be installed, the hardware configuration (kernel, partitions, encryption, ...), the system users, the Google Chrome extensions that will be installed automatically, the GTK theme... practically everything. Altering the system configuration will be as simple as modifying these files and changing the system to the new state. Furthermore, you will be able to modularize the configuration as you like thanks to the import function. Wonderful.
  - modify state of machine temporarily (like *sandboxing the entire OS*)
    - "The Nix shell is a powerful tool that allows you to temporarily modify the state of the machine. For example, you will be able to run an application without having it installed. You create a shell with that package/configuration and when you close it, it will leave no trace."
  - **steep learning curve**
    - uses a purely-functional lang (also named nix)
  - *WARNING: uses (wastes) a lot of time*
    - "all the time you spend generating this configuration, looking for the options, dealing with their inconsistencies, etc."
      - options, the *.toml-like key-value settings*, are created by the folks that package the nix package? Otherwise, you'd have to manually configure it elsewhere
  - *maintaining packages is complicated, and the crux of the whole idea of nix*
    - *WARNING: if the nix store doesn't have the package you want, you will waste days making one, let alone maintaining it*
  - **WARNING: no documentation**
    - *people just look at source code of packages, or rely on the very helpful community on discord*
  - *WFF: WARNING: just one version of most software is available (so no installing old versions, before their dev turned the wrong way)*
    - this conflicts with scripting languages which often want certain versions of dependent modules(??)
      - also the packages, and thus modules/libs must be compiled! yikes..(??)
  - it's built on linux
    - *WARNING: yet, given the amount of more things you must do, on top of a broken linux ecosystem, it's just asking for self-torture. All of linux's hardware problems: especially GPU-related, will still haunt you, but from another level of abstraction away*
  - *TODO: no games??*
  - NOTE: suggested to use (nix-)flakes
  - can start with home manager
    - "*NixOS manages system configuration but not user-related configuration. Home Manager, a project created by third parties, takes care of that.*"











TODO: TO MERGE

https://wiki.archlinux.org/title/Arch_compared_to_other_distributions

basically, the slower the release cycle, the more stable, with LTS versions being among the most stable
stable distros are more for servers, wheras "rolling-update" distros are more for personal desktop use

from most stable to least:
RHEL (costs money)
CentOS/Rocky Linux (free RHEL branch, basically LTS by nature)
Debian LTS(?) > Ubuntu LTS
Debian > Ubuntu (normal version, stable branch)
Debian (testing branch) > Ubuntu (devel branch) > Arch Linux

  
# Debian
Debian
  - more so for developers, as it won't have the friendliness of Ubuntu (software center, etc.), nor sane config defaults
  - but that means it also won't have the bloat!
  - probably a good step from Ubuntu
  - super stable, maybe even more-so than Ubuntu as it has even less features to worry about
  - two version branches: stable (for enterprise-grade tested) every 6 months and testing (for current software)
  - Debian, **abides 100% free software social contract**, thus no paid software in the package manager?
  - **completely community-based**
  
Ubuntu
  - built on top of Debian
  - has long-term-stable (LTS) releases for stability (once every two years), supported for a whopping 5 or even 10 years!!!
    - then interim releases once every 6 months
  - super stable for both server-side and desktop
  - desktop can be a tad bit bloated for some more advanced users
  - has sane config defaults
  - desktop, core, server versions
    - core only has snap, meanted for embedded devices
    - **server** doesn't come with a desktop, but is widely adopted for server use by all major cloud server companies
  - "Most Ubuntu editions and flavours simply install a different set of default packages compared to the standard Ubuntu Desktop. Since they share the same package repositories, all of the same software is available for each of them.[109][110] Ubuntu Core[a] is the sole exception as it only has access to packages in the Snap Store.[111"
    - Kubuntu, Xubuntu, etc. are just Ubuntu with different desktop environments: KDE for Kubuntu, xfce for Xubuntu, and so on
  - although free, sorta run by the company Canonical
  
Linux Mint
  - like Ubuntu, another newer beginner-friendly distro built on top of Debian
  
Pop OS
  - like Ubuntu, another newer beginner-friendly distro built on top of Debian
  - although the name is terrible, people say it's alright
  
  
# Fedora
Fedora
  - update every 13 months? or was it 6 months?, pretty short version life-span..
  - is the upstream source for Red Hat Enterprise Linux
  - Linus uses it
  
  
# Arch Linux
Arch Linux
  - abides KISS principle
  - completely customizable, no bloat
    - this can take time
  - good community, and great community-run package manager (AUR)
  - rolling release software update means very frequent updates
    - making it bad for server-side use, as stuff can break
  - install via terminal only, as it starts without a desktop
  
  
# OpenSUSE
OpenSUSE
  - Leap and Tumbleweed versions
    - Leap for on-edge rolling release
    - Tumbleweed for slow rolling release
      - a very good option to get rolling release (latest software), but in a more stable manner than Arch and Leap


# RHEL
RHEL
  - paid enterprise server product

Rocky Linux
  - successor of Cent OS, and thus on top of RHEL
  - super stable, super slow release cycle
  
Cent OS
  - on top of RHEL
  - moved to Rocky Linux, although still supported as of 2022
  
  
  
  
 
  















# customization (gui packages)
NOTE: cli apps 'n setup are listed in the-tui-dream.txt and setup.sh
the linux world is full of customization, like the way kids do for desktop computer hardware, bicycles, motorcycles, and cars.

https://www.reddit.com/r/unixporn/wiki/themeing/dictionary/#wiki_rice/
  - /r/unixporn is full of ricers suping up their desktop environments


package managers:
native package managers:
  - each linux distro has it's own package manager: apt for debian, dnf for fedora, etc.
  - checked by the people that maintain the distro
native
nix

app (like windows) package managers:
  - unchecked, includes all dependencies, making it easier for app-devs to maintain, good for bigger apps (like how Windows works?)
  - often sandboxed to make it safe from affecting the rest of the os
flatpak
x/snap(d)
  - has political problems tied to Canonical (company of Ubuntu), forcing certain apps to use snap on Ubuntu




desktop environments (DE):
  - contain everything: a windows manager, a taskbar, widgets, etc.

main:
KDE (Plasma)
  - contemporary, highly customizable
mate
  - also well-received
cinnamon
gnome
  - used by ubuntu, old feeling

lightweight:
xfce
  - very old feeling
  - often used for servers 'n old computers just to be remoted into
lxqt


custom:
compositers / WMs:
  - to put windows in the right place
sway
i3
wayland
  - used by chromeos
..?


tui file-managers:
see the-tui-dream.txt and setup.sh

gui file-managers:
https://www.reddit.com/r/swaywm/comments/ja93ss/comment/g8ojr1a/?utm_source=reddit&utm_medium=web2x&context=3&rdt=48122
They all suck in their own way.

pcmanfm
  - too basic, thunar is too basic, QT-based (pcmanfm-qt, dolphin) suffer from a disappearing menus QT bug, and dolphin is kinda bloated and practically pulls in the whole KDE suite.

Choose something you like, I prefer ranger and use pcmanfm when I have to.


krusader

task-bar:
polybar
  - easy to customize

...




