#+title: Ucsc Grad Computational Media Application


* how to apply - grad admissions

Go to https://applygrad.ucsc.edu/apply/

check elegibility for app fee waiver

you cannot make changes after you submit

recommendations must be done two weeks prior to deadline!!


** Letters of Recommendation
Three (3) letters of recommendation are required, up to 5 may be submitted.
10/9/25, 5:42 PM How to Apply – Graduate Admissions
https://graduateadmissions.ucsc.edu/how-to-apply/ 4/8
Recommendation letters must be submitted electronically through the online application. Register
your recommenders in the “Recommendations” section at least two weeks before the application
deadline.
1. Select whether or not you waive your right to review your recommendation. You must make
this selection for each recommender. This selection is final and not reversible.
2. Click the Send To Recommender button to send an email to your recommender. This email
will have secure link that they must use to submit their recommendation.
3. See our page on Letters of Recommendation for further information.
Using a letter service? (click to expand)

** The Statement of Purpose
This should be a concise, well-written essay about your background and your reasons for pursuing
graduate study in the field you have chosen. The requirements for your Statement of Purpose may
vary depending on the program you are applying to:
Go to Graduate Programs; scroll down and click on the name of the program you’re applying
to; read the page for details on what to include in your statement of purpose.
The Personal History Statement
This is required of all applicants. This statement will be used in conjunction with your application
for graduate admission and financial support. Please note that the Personal History Statement
should not duplicate the Statement of Purpose. As with the Statement of Purpose, the requirements
may vary depending on the program you are applying to:
Go to Graduate Programs; scroll down and click on the name of the program you’re applying
to; read the page for details on what to include in your personal history statement.

** Academic History and Transcripts
Provide dates you’ve attended (to and from) as well as unofficial transcripts for any college or
university you’ve attended.
Only enter in degree information (title of degree, date awarded) if you have or expect to be awarded
a degree before beginning your attendance in your first term at UC Santa Cruz as a graduate
student.
You will also provide your Grade Point Average on the application:
10/9/25, 5:42 PM How to Apply – Graduate Admissions
https://graduateadmissions.ucsc.edu/how-to-apply/ 5/8
A cumulative grade point average (GPA) for all undergraduate coursework attempted
Your most recent overall GPA for the last two (2) years of your undergraduate education
If applicable, your cumulative GPA for all graduate coursework attempted
All GPAs should include courses in which you received an F
If you need help calculating your GPA, please locate a reputable calculator online

** Document Scanning Guidelines
Scan your documents for a clear, legible, result with settings: letter size, 200dpi, less than 2.5
MB.
Scanning in “gray scale” or “black and white” may produce the best results.
Still too large? Photocopy the document, then scan that copy.
Save as a PDF file
Our application only permits these files for uploads.
For transcripts, be sure to include a single copy of the transcript legend (usually the back
page).
Do not include, or make sure you redact (cut or black out) any appearance of your Social
Security Number (SSN).
